### ISSUE TITLE
Sonar c plugins needed for sonarqube 6 version 

### ISSUE THREAD

**Issue by puneetsoni1** [SonarOpenCommunity/sonar-cxx#1041]
Hi all I installed sonar-cxx 0.9.7 version. but I think it only supported the C++. For C langaguge code which sonar plugin is compatible. Please suggest me

**Comment by guwirth** [comment]
@puneetsoni1 should also work with C code. Know from many others using it. Maybe you have to set https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxcfilespatterns to get better results.

**Comment by puneetsoni1** [comment]
Hi guwirth 
Can you tell me what should I set in configuration?

My configuration is


sonar.projectVersion=0.1_R1_B$BUILD_NUMBER
sonar.host.url=http://192.168.255.48:9000
sonar.projectBaseDir=/home/metis/.jenkins/jobs/RUT_ASW/workspace
sonar.sources=/home/metis/.jenkins/jobs/RUT_ASW/workspace
sonar.dynamicAnalysis=reuseReports 
sonar.language=c++
sonar.build-stability.username.secured=admin 
sonar.build-stability.password.secured=hsc123
sonar.c.library.directories=/home/metis/software/jenkins/jobs/RUT_ASW/workspace/mexsat/rut/inc,/home/metis/software/jenkins/jobs/RUT_ASW/workspace/mexsat/rut/application/sw/inc,/home/metis/software/jenkins/jobs/RUT_ASW/workspace/mexsat/rut/src/platform/atc/cmd,/home/metis/software/jenkins/jobs/RUT_ASW/workspace/mexsat/rut/src/platform/atc,/home/metis/software/jenkins/jobs/RUT_ASW/workspace/mexsat/rut/baseband/sw/inc
sonar.exclusions=**/*.h,**/mexsat/lost+found,**/mexsat/solaris,**/mexsat/test,**/mexsat/tools,**//mexsat/vxworks,**/mexsat/antenna,**/mexsat/components,**/mexsat/active_rel_streams.txt,**/mexsat/rut/baseband,**/mexsat/rut/test
sonar.dynamicAnalysis=reuseReports 
sonar.scm.threadCount=4 
sonar.projectKey=RUT_ASW
sonar.build-stability.days=10 
#sonar.build-stability.url=Hudson:http://192.168.0.166:8080/jenkins/job/RUT_ASW
sonar.scm.enabled=false 
sonar.projectName=RUT_ASW


![image](https://cloud.githubusercontent.com/assets/13866257/24599940/1be7c94e-1870-11e7-965c-ebfe55dac6ad.png)
![capture](https://cloud.githubusercontent.com/assets/13866257/24599966/3469def8-1870-11e7-98cf-7eecf38ffa96.PNG)

To run the cxx profile or check the code of c language what should i need to change.

**Comment by jmecosta** [comment]
@puneetsoni1 you can give a try to the sonar-c plugin -> it will be available for download here https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/build/588/artifacts sonar-c-pluging.jar

the following needs to be changed in your configuration, 

1) take both sonar-c and sonar-cxx into use
2) after restart the server go to global options and remove the extensions from c from the cxx plugin. These are sonar.cxx.suffixes.sources and sonar.cxx.suffixes.headers. Save
3) you can create a new profile for c if some rules are not relevant (optional), the cxx lint rules are disabled by default
4) in you properperties file for the project you are analysing remove sonar.language since this will for sonar only to analyse c++ files

if all goes well, you should see metrics for c and c++ togher in sonar ui

good luck

**Comment by jmecosta** [comment]
#1100 dedicated plugin now available
