### ISSUE TITLE
Most Violated rules and components in sonarqube 6.0

### ISSUE THREAD

**Issue by puneetsoni1** [SonarOpenCommunity/sonar-cxx#1073]
Hi all. I want to add widget Most Violated rules and Most violated Components in Sonarqube 6.0. As i see these comes with issue density plugin and violation density. As both are deperceted for sonarqube 6.0. Any alternate method can anybody suggest....

**Comment by jmecosta** [comment]
hi, widgets are remove from sonarqube 6.3 and above. so there is not much point on investing on those erb widgets. 

6.3 brings a new method to inject javascript pages in the ui. from there you can create your own widgets  that get you that data. 

i suggest you open a question on the sonar gougle groups forums, since this is a not really related with the cxx plugin
