### ISSUE TITLE
Refactoring: Size of plugin jar: optimize dependencies in POM files

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1074]
Our plugin is very big compared to others. Does someone know the reason? I'm not so familiar with dependency analysis. 

@jmecosta for my understanding cxx-lint is included in the plugin with about 10mb. Is this necessary?

**Comment by jmecosta** [comment]
@guwirth the cxx lint will double the size of the plugin, since its needs to run standalone. What i think its odd is that the all thing takes 10MB. The CxxLint has depend to the cxx-checks (110K) and by itself its only 2 source files. The rest is comming from dependencies.  This problem affects both the cxxlint and the cxxplugin so perhaps we should take a deep look at the dependencies and try to do a hair cut.

its important the linter is included in the plugin itself, since its the only way we make sure both server and local analysis are alligned and produce same results.

ive checked the java plugin and javascript plugins that do have sslr, and they are 3M and 1.3M. The default size for the cxx plugin is now 5MB. So maybe we can also check if we can reduce the 5MB

summary:
plugin itself 5MB 
cxxlinter 7MB

i try to see if we can make the linter smaller and we should try also to make the plugin itself smaller

**Comment by guwirth** [comment]
@jmecosta are you familiar with dependency optimization? Are there tools or a description? Should dependencies be optimized starting from parent (plugin) or from children (squid, checks, ...)?

**Comment by jmecosta** [comment]
@guwirth i  think the dependency optimization will help in the sonar-plugin side only. here im am not very familiar how we can clean up those there. a good exercise is to take the linter and then investigate if we can exclude depencies. it might be a bit hard since the only way to tests this is to run a analysis so loads of deployment of the plugin (we have seen many issues with guava for example).  Regarding this parent to children im not very proficient on that (but it think you can handle all this in the cxx-plugin project pom.xml), sinze the size of our libs  (checks and squid 150Kb both) is very small. Then there is jump on the plugin side to 5MB. ive looked in the jar, the problem is the loads libs that are included in the MANIFEST/lib folder, the javascript plugin for example does not have any of those, so we might start by looking why we have them in first place. That should bring the plugin to under 2M for sure. 

The biggest ones there are guava (1.4M) that we can likely reuse from core and ant (1.9M) that seems that we use only because of directoryscanner in CxxReportSensor. I would start by these 2 for now


on the linter we need to have the full application there so with all the dependencies (there are no libs in cluded in jar only classes of dependencies). there seems to be a tool https://www.guardsquare.com/en/proguard that can help on shrinking the artifact by applying obfuscation and such. So far i was not very successfull on working with it. i will continue to investigate to see i can bring even the size lower there.

**Comment by jmecosta** [comment]
@guwirth for the ant directoryscanner we can try https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-utils/3.0.9 https://maven.apache.org/shared/maven-shared-utils/apidocs/org/apache/maven/shared/utils/io/DirectoryScanner.html 

no dependencies and the size is only 250K here we save already 1.5M

**Comment by felipebz** [comment]
Hi! I just saw this issue and I think I can help.

I [reduced the size of my plugin](https://github.com/felipebz/sonar-plsql/commit/1317a31e40b7b6ac388ab807b104dd78ed2dcd0a) just using the maven-shade-plugin to package the jar. I did some tests with sonar-cxx and I found out that it's possible to save 3 MB from the plugins.

I'll send a pull request with the changes. ;-)

**Comment by guwirth** [comment]
POMs are up to date with 1.2.2.
