### ISSUE TITLE
Sample project for cmake build environment

### ISSUE THREAD

**Issue by fkromer** [SonarOpenCommunity/sonar-cxx#1127]
Does anyone know about some tutorial or alike about how to use sonar-cxx in a project with a cmake build environment? I would be interested in contribution to port [this make build project](https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/samples/SampleProject2) to a cmake build project (including updating to current gtest version, etc.)...

**Comment by jmecosta** [comment]
Check the wiki https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis you should be able to run an analysis regardless of the build system

**Comment by fkromer** [comment]
I found the [page about running the tools](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-tools) required prior to running the analysis (just pulls together the results). A sample project would make it easier to understand this integration part...

**Comment by jmecosta** [comment]
You have in that page the minimal commands for the tools. That is as good
as a sample. It's not easy to create a sample since everyone uses different
tools with different options.

The main point of all this is that you need to configure the tools to
provide the best results. The best is to consulte the documentation I'm
each tool website.

Since the plugin does not run any tool the samples we provide are only to
describe the import part.

**Comment by fkromer** [comment]
For Project2 is it ok to use [Ubuntu gcovr](https://launchpad.net/ubuntu/+source/gcovr) instead of gcovr.py?

**Comment by jmecosta** [comment]
No idea, you need to check if the format of the xml report is the same as
with the python script.

**Comment by guwirth** [comment]
@fkromer please reopen if still an issue.
