### ISSUE TITLE
Writing a SonarQube plugin that extends sonar-cxx

### ISSUE THREAD

**Issue by gena01** [SonarOpenCommunity/sonar-cxx#1192]
Hi @guwirth, I want to try a little experiment and see if I can write a plugin that extends sonar-cxx. What is the proper way to get this going? Is the latest release available in maven? How do I pull it in as a dependency in pom.xml?

Thank you,

Gena01

**Comment by guwirth** [comment]
@gena01 that depends a little bit what you want to do. 
* Is it an additional sensor as part of the existing plugins?
* Is it an extra plugin? Here you should also think about if https://github.com/SonarSource is not the better place?

What exactly are you planning?

**Comment by gena01** [comment]
At this point just trying to hack something together. I am thinking a separate plugin that extends sonar-cxx with custom sensor and supporting classes.

**Comment by gena01** [comment]
@guwirth I guess sonar-cxx is not published to maven repository. Any plans to start doing that? This way I can use it as a dependency and have mvn pull in the right info?

Also looks like 0.9.7 api is quite different from current master. I am not sure which to base things on right now. Any plans to have more releases sooner (last was in February)?

One hack that seems to work for me is just using "c++" language key for the stuff I am messing with, but if I'll get to the point of having to pull in other things I am not quite sure yet as to which route to take.

**Comment by jmecosta** [comment]
@gena01 its still not clear what you want to do. the current master has been refactored so that it supports having multiple c/c++ plugins

-> cxx-squid is the grammar
-> cxx-sensors is where all sensors are implemented
-> cxx-checks is where checks are, that you can also extend on its own

if you are planning to creating a new language plugin. you need to be carefull with the "c++" as duplicated keys are not allowed, then it should be possible for you to just install those artifacts locally and create a new plugin based on the sonar-c-plugin or sonar-cxx-plugin

if you are planning to create a new sensor, take a look at the external sensor first, since the idea is to import any custom reports without the need to creating a dedicated sensor.

publishing in maven central hasnt been discuss earlier, and im not sure its in the plans. Since publishing in maven requires also that we have a stable api that we dont have.

**Comment by jmecosta** [comment]
@gena01 also you cant have 2 plugins consuming the same type of files. so if you custom plugin will define the extensions to consume has .cpp then it will fail to start the server if the cxx-plugin is installed.
