### ISSUE TITLE
Sonarqube 6.5 - Undocumented API Rule Not Working

### ISSUE THREAD

**Issue by ericross518** [SonarOpenCommunity/sonar-cxx#1248]
Undocumented API detection does not appear to be working in Sonarqube 6.5. I assigned the rule "Public types, methods and fields (API) should be documented with Javadoc" to a Quality Profile and set it to the default profile for Java. After running sonar-scanner, nothing is flagged, even though methods in the code are missing Javadoc.

**Comment by guwirth** [comment]
@ericross518 thanks for the feedback. 

Reading the issue I'm not sure if you really talking about c++ because you wrote Javadoc and Java profile?  This forum is about C++. 

Are you the documentation metric missing or are there no more issues? I know that they removed at least the docu metric in one of the newer versions.

If you are talking about C++ provide a sample please. Otherwise ask in the official SonarQube forum https://www.sonarqube.org/community/.

**Comment by ericross518** [comment]
Sorry, I have not posted to the right location.   This is a SonarQube,
sonar-scanner, Java rule issue, not a C++ issue.   I'm aware the
documentation metric is missing, but it seems the rule is also not working.

I reposted to the SonarQube forum.
