### ISSUE TITLE
C plugin usage

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1251]
Hi, 

There is a new **C plugin** as part of our repository available for some time.
* Who has already some experience with it? Can you share you experience with us please?
* Who has already both cxx and c plugin in parallel in use? Is this working as expected?

Latest snapshot versions are available here:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Regards,

**Comment by guwirth** [comment]
@jmecosta is the plugin on your side in productive use?

Wondering how this is working in
* mixed projects with c / cpp files?
* same header files in use by c and cpp file?

**Comment by jmecosta** [comment]
@guwirth when implementing the feature i started using it but after upgrading to last version of SQ i had to disable it since the server was not starting. So i will need to look at this sometime soon. 

the idea is that you need to adjust the extensions in a way they dont clash. 

i will try to get this working before the next release

**Comment by guwirth** [comment]
@jmecosta thanks for your answer. I'm wondering how header files (.h, .hpp) are handled if they are assigned to c and cxx plugin. because they are assigned to both plugins then.

* Which rules are used?
* Are issues assigned twice?

Any experience?

**Comment by SonarOpenCommunityAdmin** [comment]
basically you will have 2 different profiles that you need to maintain. the key here is to decide what is c and what is c++ since they cannot be defined in both plugins. 

i was doing 

c -> .c, .h
c++ -> .cpp .hpp

after that it should work as normally with no duplicated issues i think. the rules we just copied the profiled from c++ but thats is really not good and needs to be worked on

**Comment by jmecosta** [comment]
basically you will have 2 different profiles that you need to maintain. the key here is to decide what is c and what is c++ since they cannot be defined in both plugins.

i was doing

c -> .c, .h
c++ -> .cpp .hpp

after that it should work as normally with no duplicated issues i think. the rules we just copied the profiled from c++ but thats is really not good and needs to be worked on

**Comment by jmecosta** [comment]
looks good in a clean installation

![image](https://user-images.githubusercontent.com/1041352/31779538-04ba0628-b4fc-11e7-9ea2-1f7f832a97fd.png)

the only thing i need to do is to put in sonar properties
sonar.cxx.suffixes.headers=.hxx,.hpp,.hh
sonar.cxx.suffixes.sources=.cxx,.cpp,.cc

**Comment by guwirth** [comment]
@jmecosta but in real world .c and .cpp are both using .h files (and often the same)

**Comment by jmecosta** [comment]
I dont think there is a problem with that, since there is no duplication

**Comment by guwirth** [comment]
@jmecosta think you are right. For issues there are no duplicates.

In general I see the following use cases now:

1.  Someone want to use the c plugin `or` the cxx plugin only: This case should be the easiest and work as of today. For the c plugin the setting `sonar.cxx.cFilesPatterns` should not be available and per default active.

2. Someone want to use the cxx plugin only to compile .c and .cpp files. Both should be compiled and handled as a C++ compiler is doing it: `sonar.cxx.cFilesPatterns` should not be used.

3. Someone want to use the cxx plugin only to compile .c and .cpp files. .c files should be handled as C compiler is doing it and .cpp files should be handled as a C++ compiler is doing it: `sonar.cxx.cFilesPatterns` should be used.

On long run we should be able to remove `sonar.cxx.cFilesPatterns` because case 3 could be handled by c plugin.

**Comment by jmecosta** [comment]
ok makes sense. so we should still remove cFilesPatterns from the c plugin already? since it does not make sense to keep it?

**Comment by guwirth** [comment]
Proposal is to remove c plugin and integrate functionality in cxx plugin. Commercial plugin shows that one plugin can support more than one language.

**Comment by jmecosta** [comment]
Interesting, is this something new? I tought one jar could provide only one
plugin, since it the pom you need to specify the plugin class.

If the mingle all stuff into a class does it not make the all stuff more
complex and more complex to maintain? That is if you can't have a dedicated
class there for it

**Comment by guwirth** [comment]
@jmecosta as far as I know the commercial plugin is only one JAR containing / supporting the languages C, C++ and Objective-C.

**Comment by guwirth** [comment]
@jmecosta 

> since it the pom you need to specify the plugin class. 

Where is this in the POM?

> ...complex and more complex to maintain?

Not sure but today we have to maintain two plugins. Grammar behind is anyway the same it's only to show issues and metrics under different languages?

**Comment by guwirth** [comment]
@jmecosta as you can see it's one plugin containing several languages:
![image](https://user-images.githubusercontent.com/6077367/35412177-a2188cf2-021b-11e8-8c56-23760dd70459.png)

**Comment by jmecosta** [comment]
Interesting how they handle the metrics per language.  Maybe it's all the
same for them. The idea of the C plugin was that we could have different
metrics per language.  If we can still have them then I don't see why we
can't just merge everything

**Comment by guwirth** [comment]
@jmecosta structure is like this

**C / C++ / Objective-C**
- `Language`
   - `C++`
      - key: `cpp:nnnnn` (e.g. cpp:S3805)
   - `C`
      - key: `c:nnnnn` (e.g. c:S3805)
   - `Objective-C`
      - key: `objc:nnnnn` (e.g. objc:PPBadIncludeForm)

**C++ (Community)**
- `Language`
   - `c++`
      - key: `cxx:nnnnn` (e.g. cxx:UseCorrectInclude)

**Comment by jmecosta** [comment]
That's for profile definition a plugin can have as many as he wants.

The problem was always  you could only define a plugin per jar. But if
that's not the case anymore then merging those together makes sense.  The
split was only to allow this

**Comment by guwirth** [comment]
@jmecosta for my understanding it is like this:

- jar <=> plugin 1:1
   - plugin key must be unique
   - plugin <=> language 1:n
      - language: unique key, unique file extension
   - plugin <=> sensor 1:n 
      - sensor: general, one or more languages
   - plugin <=> profile 1:n
      - profile <=> language 1:1
   - plugin <=> repository 1:n
      - repository <=> language 1:1

**Comment by jmecosta** [comment]
yes, but how do you workaround this:

https://github.com/SonarOpenCommunity/sonar-cxx/blob/f10e60b0c9a965608ede2be4ed70f5c9d6080f25/sonar-cxx-plugin/pom.xml#L21

my understanding was that this was needed to defined the plugin, so we have 2 plugins inside the jar. will it work? if it does then all good, but i have tried this scenario

**Comment by guwirth** [comment]
@jmecosta the commercial plugin is called `SonarCFamily `and have `C`, `C++` and `Objective-C` language inside. This seems to be the trick?

**Comment by jmecosta** [comment]
Three jars inside one jar? Can that be the trick

**Comment by guwirth** [comment]
@jmecosta as you can see it's one plugin containing several languages:
![image](https://user-images.githubusercontent.com/6077367/35412177-a2188cf2-021b-11e8-8c56-23760dd70459.png)

**Comment by jmecosta** [comment]
Ok so basically is how it was earlier? So the plugin consumes any file of
type c, c++, etc.

So I suppose that is the way to go.

**Comment by guwirth** [comment]
@jmecosta think your original use case was to split C and C++ issue and metrics and handle it as two languages? There was no other reason, or?

**Comment by jmecosta** [comment]
Yes that's was the idea.

**Comment by 1FiniUm** [comment]
Hi, 
I use the c plug-in 1.0.0 in production with SonarQube Version 7.1,
I have a problem with the configuration property : sonar.c.cppcheck.reportPath
It seems not working as I don't see the Cppcheck sensor in the sonar Scanner log, and the cppcheck issues in SonarQube

**Comment by 1FiniUm** [comment]
@guwirth thx for your help, I launched the runner in debug and you are right :

> 11:00:46.915 DEBUG: 'C (Community) CppCheckSensor' skipped because there is no related rule activated in the quality profile

The default sonar profile (Sonar way 674 rules) is used and all the cppcheck rules seems activated.
Maybe I miss something in the profile configuration to enable cppcheck rules?

**Comment by 1FiniUm** [comment]
@guwirth It's fixed now, you were right, I created a new profile and all is good now.
Thx, for your help :)

**Comment by spashx** [comment]
Hi,

We have a fresh new SonarQube 6.7.4 LTS version installed with the commercial C/C++ plugin installed (sonar-cfamily-plugin-5.1.0.10083.jar).

When copying the community plugins and restarting Sonar, we have this issue:
`java.lang.IllegalArgumentException: There is already a quality profile with name 'Sonar way' for language 'c'`
If the sonar-c-plugin-1.1.0.jar is removed from the folder, Sonar is working again.
It looks like  the community plugin tries to use/generates the same profile name as the commercial C/C++ plugin for the c langage, which is now read only, as stated in the SonarQube documentation: https://docs.sonarqube.org/display/SONARQUBE67/Release+6.5+Upgrade+Notes

Is there a way to modify the default profile name of the c community plugin, like it is already for the C++ (seen as  "C++ (Community)") ?
Thanks.

**Comment by ivangalkin** [comment]
Hi @spashx,

please se #1433, especially comments made by @guwirth

**Comment by guwirth** [comment]
@1FiniUm see also #1345 

By the way: what advantage do you see by using the c plugin? You can do the same by using the cxx plugin and set https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxcfilespatterns.

**Comment by spashx** [comment]
@guwirth not sure to understand 100%, you mean the cxx plugin with c file patterns setup will behave exactly like the c one ?

**Comment by ivangalkin** [comment]
@spashx at this moment, the [almost*] only advantage of the c-plugin is the mapping of ".c" extensions to the distinguished C-Language. If you use both C++ and C plugin you can differentiate between C-Language and C++-Language. E.g.  [NC]LOC are counted separately, you can filter either for C or for C++ issues etc.

(*the set of rules for the squid sensor is slightly different for c and c++ languages, but it's not that important IMHO.)

The disadvantage of having both plugins enabled is the fact, that you have to maintain both rulesets separately for C and C++ (although de-facto the rules are absolutely the same).

If the appearance of C in the web UI in not important for you, you just can use the mentioned parameter `sonar.cxx.cFilesPatterns` in the cxx plugin.

**Comment by spashx** [comment]
@guwirth  ok thanks for clarification.

Coming back to initial requirement, in SonarQube 5.6.6 we were using both commercial and community C plugin because the community one has features like integration of external tools outputs like Valgrind, RATS,etc.. that the commercial edition does not provide. 
With the latest update of the community C plugins, it is no more possible.
Perhaps the best approach could be to rename the community C profile to ensure no naming conflict with the built in profile for C of the SonarSource C/C++ plugin.

eg: "C++ (Community)" for cxx and "C (Community)" for c.
This way it is possible to use both C plugins at the same time and avoid C/C++ mixup in the UI.

**Comment by spashx** [comment]
Hi,
I'm coming back about the issue of begin unable to  deploy the C Community plugin into a SonarQube instance already having the C++ Commercial plugin. This still happens with release V1.1.0 and SQ 6.7.5.

The C community plugin will fail to load because it duplicates the C / Sonar Way default profile name of the C++ Commercial plugin. This does not happen with the C++ Community plugin.

I know that I could only install the C++ Community to make C Community analysis, but in this case we are not able to distinguish language analysis in the UI.

Looking to the V1.1.0 release, I see that it already includes a fix for that ([merge ](https://github.com/SonarOpenCommunity/sonar-cxx/commit/afbee7b0fb8812d13c72d7cac51558ecd7f854c6#diff-c592d668c90e5a99fbebdfacd3a09a96 )of pull request #1433), but it simply does'nt work with the C community plugin.

- the C++ Community really appears in sonar as C++ (Community) as expected
- the C Community is unable to load because of duplication.

If I modify the default-profile.xml file of sonar-c-plugin-1.1.0.jar and rename the default language "c" to "C (Community)" as defined into CLanguage.java, the plugin will load, and the language shown as "C (Community)"
but I assume this is not the proper way to dot it since in the sonar-cxx-plugin-1.1.0.jar's default-profile.xml the language is set to "c++" and not "C++ (Community)".
 Is this a typo into default-profile.xml files that should contain same strings for languages as the hardcoded ones into CLanguage.java/CppLanguage.java or do I miss something else ?

Thank you.

**Comment by jmecosta** [comment]
Can you create pull request? Hard to test if not having a instance with the
payed plugin

**Comment by guwirth** [comment]
Duplicate, see #1400
