### ISSUE TITLE
cppcheck syntax error

### ISSUE THREAD

**Issue by sgithubs** [SonarOpenCommunity/sonar-cxx#1286]
1. I have checked my code by cppcheck version="1.81".
2. I Have added cppcheck-result.xml to sonar.cxx.cppcheck.reportPath.
3. I got an syntax error on my SQ v.6.5 like this:
Syntax error
Cppcheck cannot tokenize the code correctly.
4. Such error on line 1 in cppcheck-result.xml report file
5. C++ plugin version: 0.9.8-SNAPSHOT
6. Because of this error, file cppcheck-result.xml have added to my SQ scan to "Code Smell" but I don't want to scan this file. Also, I don't want to add such file to sonar.exclusions.

Could you please help me with this?

![image](https://user-images.githubusercontent.com/22050323/32443335-5047b202-c307-11e7-87de-f8e855845c20.png)

**Comment by guwirth** [comment]
Hi @sgithubs,

please have a look here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
Cppcheck is working we also have an integration test for it: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project

Would anyway use file format V2.

Regards,

**Comment by guwirth** [comment]
@sgithubs think understood your question wrong. Problem is during XML check and not CPP check. Think this is the wrong forum then.

**Comment by sgithubs** [comment]
Oh...
I am being redirected from one to another.

Here is the answer from sonarsource.com SonarXML:
Serg, this is not the right place to ask for help with SonarSource plugins. Beyond that, neither cxx, nor cppcheck are SonarSource plugins. You probably want to look for the cxx analyzer on GitHub and open an issue there. (https://jira.sonarsource.com/browse/SONARXML-62)

I can not understand who to turn to for help?

**Comment by guwirth** [comment]
Hi @sgithubs,

* First of all you have to create the cppcheck XML report. Please validate the resulting XML file with e.g. an XML Online Validator. In case there is a problem creating the XML report ask the Cppcheck community for help.
* Create an Cppcheck format with file format 2. How to do this and a sample XML is here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers. 
* Second try to read your XML report into SonarQube. Using the community plugin you have to use `sonar.cxx.cppcheck.report` setting in the config file. Please locate the report file outside of the project root folder. Otherwise the XML plugin tries to import and validate the report file too.
* In case of problems most likely the file encoding of the XML file is wrong. 

Good luck.
Regards

**Comment by sgithubs** [comment]
Thanks, @guwirth for your answer.
I have done all steps but the problem still exist. 
As result, I will save report not in the project's root directory.
Only this decision will help me :(
