### ISSUE TITLE
sonar.cxx.jsonCompilationDatabase not working?

### ISSUE THREAD

**Issue by sweetim** [SonarOpenCommunity/sonar-cxx#1304]
I am currently using Sonar cxx v0.9.8
I found that the `sonar.cxx.jsonCompilationDatabase` config is not working?
When i run the `sonar-scanner` it still complains about 

- `cannot find the sources for '#include <iostream>`

The compile_commands.json file

```
[
{
  "directory": "/home/tim/Desktop/learn/multi-cmake/build/cmake-test/src",
  "command": "/usr/bin/c++  -DIS_TESTING=\"\\\"this is macro\\\"\" -DMACRO_VERSION=2.13 -I/home/tim/Desktop/learn/multi-cmake/cmake-test/lib  -std=c++11   -o CMakeFiles/hello.dir/main.cpp.o -c /home/tim/Desktop/learn/multi-cmake/cmake-test/src/main.cpp",
  "file": "/home/tim/Desktop/learn/multi-cmake/cmake-test/src/main.cpp"
}
]
```

May I know do I still need to configure the `sonar.cxx.includeDirectories` or the `jsonCompilationDatabase` should handle all these automatically?

**Comment by guwirth** [comment]
@sweetim I'm not really familiar with this feature. Maybe you can turn debug info on to get more help (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information). As far as I know the -I parameters are used to `create the sonar.cxx.includeDirectories`. Or maybe it's #1215?

**Comment by sweetim** [comment]
Yes, it is related to it, anyway to fix it?

I try to include those directories with `sonar.cxx.includeDirectories` but I found that it will get overridden by `sonar.cxx.jsonCompilationDatabase`

**Comment by jmecosta** [comment]
@sweetim https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/test/resources/org/sonar/cxx/sensors/json-compilation-database-project/compile_commands.json check that file for the format of that should be expected.

#include <iostream> is a system header so you will need to use 

		"_comment_" : "example extension to define global defines and includes for headers and for files which are not compiled",
		"file" : "__global__",
		"defines" : {
			"GLOBAL_DEFINE" : "1"
			},
		"includes" : [
			"/usr/include"
			]

in start of the db to pass the system directories

**Comment by guwirth** [comment]
@sweetim please read also our wiki: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#json-compilation-database-format-specification-support

**Comment by guwirth** [comment]
@vesajaaskelainen is this `__global__` something cxx plugin specific or part of the JSON compilation database definition?

**Comment by vesajaaskelainen** [comment]
@guwirth extension to JSON compilation database only used(?) in cxx plugin. This is a workaround as cxx plugin does not use "compilation process" for header analysis so that it could capture different definition/include sets when analyzing headers. Now this __global__ definition is used for more or less for all headers.

**Comment by guwirth** [comment]
@vesajaaskelainen thanks for your answer. We already discussed here in the past a solution to set system include files and local include files with different configuration properties. One solution could be to define one more property beside `sonar.cxx.includeDirectories` for system includes, e.g. `sonar.cxx.systemIncludeDirectories`. JSON compilation database would change then only  `sonar.cxx.includeDirectories` and `__global__` only `sonar.cxx.systemIncludeDirectories`. Optional they could also be defined in the configuration file then.

**Comment by vesajaaskelainen** [comment]
What we do with Klocwork is to use it capture build process as it scans for both user provided command line options (what is now in JSON compilation database example above) and also compiler internal defines and includes. Latter is needed to get proper analysis done, usually in command line there isn't many settings (at least in our cases). When we have those settings then we will utilize other extension that uses defines and includes instead of command line part. With this information we get decent analysis from cxx-plugin.

What we do for __global__ is composite of all defines and includes from all files.

We is problem still in out system is that it does not differentiate with system vs. user includes they are just combined in defines/includes fields.

Problem with sonar.cxx.systemIncludeDirectories and matching setting for defines is that there are lots of options there.

Also another problem with if one would make __system__ or __common__ is what tool is used to fill the info.
