### ISSUE TITLE
Refactoring: update wiki (documentation)

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1407]
Update our wiki documentation in wiki. Our plugin is not usable without the wiki.

* restructure wiki to find better the content: sorted by e.g. tools, sensors, metrics, ...
* remove outdated parts from preceding versions

**Comment by ivangalkin** [comment]
Hi @guwirth, hi All,

at least two issues (#1518 and #1521) were opened because of missing documentation about rules activation. I've added a new page. Please review:

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules

This link was added to the following pages:

* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers

I believe we also can add some tracing code, which could inform the user if the sensor was deactivated because of deactivated rules.

**Comment by ivangalkin** [comment]
> I believe we also can add some tracing code, which could inform the user if the sensor was deactivated because of deactivated rules.

this part is already done, please ignore

see messages like
```
'CXX (Community) XXXXSensor' skipped because there is no related rule activated in the quality profile
```

**Comment by guwirth** [comment]
V1.2: wiki needs urgent an update. Would sort everything by sensors

* Sensor XY
  * Description
  * How to create report for the sensor
  * How to configure plugin to read report
* Sensor NM
  * ...

**Comment by guwirth** [comment]
Done can be reviewed
