### ISSUE TITLE
Jenkins Sonar Scanner “Load Active Rules” sometimes takes 40 minutes

### ISSUE THREAD

**Issue by amitkumar2283** [SonarOpenCommunity/sonar-cxx#1457]
I have jenkins Job which use Sonar Plugin to execute sonar scanning and analysis. There is a step in the execution which is termed as "load Active Rules". This step sometimes takes 2 minutes to complete, and sometimes it takes upto 40 minutes. The Build slave, sonarqube server, the project Key and the Profile are always unchanged.

Can anyone help me in understanding What could be reason behind this? Could this be a problem with a Sonar server config Or jenkins/Plugin config?

- Sonar Plugin version : 2.2.1
- Sonar server : 5.6.6
- Cxx version : 0.9.8
- Jenkins version : 2.60.3

**Comment by guwirth** [comment]
Hi @amitkumar2283 this seems to be a generic SonarQube core problem. Looking where the message comes from I found:

https://github.com/SonarSource/sonarqube/blob/c0d2705e610d771b8c66ef22e64530c7bca4f538/sonar-scanner-engine/src/main/java/org/sonar/scanner/rule/ActiveRulesProvider.java

Seems that the scanner is downloading all active rules to the local PC before he is starting to scan. There seems to be also no cache. So this happens with every scan again. Think this is especially a problem with our C++ plugin because here you are able to activate/add more rules than in the other plugins.

Would recommend you to ask the SQ guys in there forum for help.
