### ISSUE TITLE
US: Support Cppcheck 1.84

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1490]
As an user I like to use the messages/issues of the latest Cppcheck 1.84 version.

Add 1.84 rules to https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml and test it.

**Comment by ivangalkin** [comment]
Hi all,

I volunteer for implementation of this US

Regards

**Comment by ivangalkin** [comment]
looks like I was too eager about the new (but unreleased) version of cppcheck. I will provide the new rule-set as far the new version will be available.

**Comment by amai2012** [comment]
BTW, some rules within cppcheck don't appear within `--errorlist` see https://trac.cppcheck.net/ticket/7772.

**Comment by ivangalkin** [comment]
Hi @amai2012,

thank you for the information.

1. I recognize at least some of the rules in the [mentioned ticket](https://trac.cppcheck.net/ticket/7772). Opening a bug for them is wrong, because they are part of [external] library configurations. If one wants to have the rules descriptions for such issues, not only the `--errorlist` but also `--library=<path_to_library_configuration.cfg>` must be passed to cppcheck. We successfully import such rules since cxx-sonar version 1.0 (see #1445)

2. We rely on the cppcheck's functionality for exporting rules. If from some reason it *really* doesn't work properly,  opening a defect for cppcheck is the only reasonable solution IMHO. I don't think, that reverse-engineering of cppcheck's code is a good idea. That's the reason by the way, why we don't import the rules from cppcheck's addons. They just do not have the export functionality (see #1439)

Regards,
