### ISSUE TITLE
V1.1 release notes draft

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1502]
**Please review, something wrong or missing?**

We are pleased to announce the SonarQube C++ Community Plugin version 1.1.0.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.2 support #1491
- minimal supported SQ API is 6.7 #1317
- add function complexity and size metrics #1398:
  - new metrics:
    - Complex Functions: Number of functions with high cyclomatic complexity
    - Complex Functions (%): % of functions with high cyclomatic complexity
    - Complex Functions Lines of Code: Number of lines of code in functions with high cyclomatic complexity
    - Complex Functions Lines of Code (%): % of lines of code in functions with high cyclomatic complexity
    - Big Functions: Number of functions with too many lines
    - Big Functions Lines of Code: Number of lines of code in functions with too many lines
    - Big Functions (%): Number of lines of code in functions with too many lines
    - Big Functions Lines of Code (%): % of lines of code in functions with too many lines
    - Lines of Code in Functions: Number of lines of code in function bodies
  - new configuration properties:
    - `sonar.cxx.funccomplexity.threshold` / Cyclomatic complexity threshold:<br>Cyclomatic complexity threshold used to classify a function as complex
    - `sonar.cxx.funcsize.threshold` / Function size threshold:<br>Function size threshold to consider a function to be too big
- Testwell CTC++ support (Verifysoft Technology GmbH) #1486
  - add coverage sensor 'Testwell CTC++' for textural reports
- Cppcheck 1.84 support #1490  #1495
- refactoring #1499 #1498  #1496  #1487 #1482 #1481

# Bugfixes

- Highlighting error for concatenated strings on multiple lines #1468 #1480

# Know Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppckeck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only
- Symlinks are not supported.

# Thanks ....

go to all contributors (in alphabetical order):

@ericlemes
@guwirth
@ivangalkin
@rufinio

... and all people which were active on the issue tracker!

**Comment by rufinio** [comment]
compability -> compatibility

**Comment by ivangalkin** [comment]
unrelated to the text itself, but still. I suspect, that the #1398 slows down the analysis tremendously; have you tested the 1.1.0 on your productive systems?

**Comment by ericlemes** [comment]
I just found some typos like cppckeck.

Regarding the speed of the analysis, it worth mentioning that these new metrics just adds some more visitor in the existing parser. It doesn't do any extra parsing and shouldn't be more expensive than the existing checks for line and cyclomatic complexity.

I'm using this in production for 6+ months in codebases with more than 1 million lines and my analysis runs no more than an hour for codebases this big.

What really slows down and even blows up the analysis for big codebases is version control integration.

**Comment by ivangalkin** [comment]
@ericlemes regarding the overhead: I will try to figure out, what is the real cause in my case. Currently I suspect the function `TooManyLinesOfCodeInFunctionCheck.getNumberOfLine`, since it is invoked at least 2 times for each function (`TooManyLinesOfCodeInFunctionCheck`, `CxxFunctionComplexitySquidSensor`) and goes through **each token**. 

The least one can do is to store the aggregated function complexity for each `CxxGrammarImpl.functionBody`. An other idea is to do something like

```JAVA
  public void init() {
    subscribeTo(CxxGrammarImpl.functionBody);
  }

  @Override
  public void leaveNode(AstNode node) {
    SourceCode sourceCode = getContext().peekSourceCode();
    int lineCount = ChecksHelper.getRecursiveMeasureInt(sourceCode, CxxMetric.LINES_OF_CODE);
    ....
  }
```

... the only disadvantage is that it counts the lines for both opening `{` and closing `}`.

**Comment by guwirth** [comment]
@ivangalkin ok wait for your feedback.

**Comment by ericlemes** [comment]
@ivangalkin I agree with you on that one and that function is definitely being called twice.

It would be a weird thing sharing state between the check and the sensor from the maintanability perspective, but for performance is a good idea.

I personally don't like the idea of counting the brackets as lines of code, since it will distort a bit the other number that are based on lines of code.

**Comment by guwirth** [comment]
Hi @ivangalkin,
Is the performance issue release critical? v1.2 is planned for July 27th with SQ 7.3.
Regards,

**Comment by ivangalkin** [comment]
Hi @guwirth, hi @ericlemes,

I couldn't perform any reliable measurements, it looks like my setup is very unstable. If you do not observe any performance issues, probably it's just me.

I would be still very grateful if you could take a look at #1503. Obviously I cannot say if it reduces the overhead or not. If you have time to perform any (basic) benchmarking, that would be great.

Regards,

**Comment by guwirth** [comment]
> I observe +4 hours after update 1.0.0 -> 1.1.0

@ivangalkin what's your overall time for the analysis?

**Comment by ericlemes** [comment]
My benchmarks:

Environment:
SonarQube 7.2
sonar-scanner-cli-3.2.0.1227-windows
Internal DB
Code base size: ~500k LoC

Scanner cmd line:
set SONAR_SCANNER_OPTS=-Xmx20g
C:\Software\sonar-scanner-cli-3.2.0.1227-windows\sonar-scanner-3.2.0.1227-windows\bin\sonar-scanner.bat -Dsonar.sources=. -Dsonar.projectKey=project-1 -Dsonar.verbose=false -Dsonar.log.level=WARN -Dsonar.language=c++ 

Plugin 1.0.0, 1st round (no cache)
Scanner time: 37.05 min.
CE time: 5 min.

Plugin 1.0.0, 2nd round (with cache)
Scanner time: 7 min.
CE time: 5 min.

Plugin built from ivangalkin/getNumberOfLine, 1st round (no cache)
Scanner  time: 33 min
CE time: 8 min.

Plugin built from ivangalkin/getNumberOfLine, 2nd round (with cache)
Scanner  time: 8 min
CE time: 6 min.

My conclusions:
- It is really hard to benchmark sonar runs, because it has a lot of variables.
- Usually when things are slow, java VM heap size is the main issue. If the memory is full and GC starts trying to collect, it is not usual that your process will get stuck for days, not hours (it happened with me, trying to analyse Unreal engine. I had to break down in 3 projects to get that analysed).
- There's a massive variation in time from the 1st run and next runs.

**Comment by ericlemes** [comment]
@guwirth I mean 1.0.0, downloaded from the releases page, latest one. Then, since there's no build from 1.1.0, I've got the one from @ivangalkin 's PR.

**Comment by ivangalkin** [comment]
@ericlemes thank you for your efforts; I agree with you, that the benchmarking for the whole analysis is

* not really reliable
* not really meaningful

It would be better to profile the analysis, to identify the performance issue, continuously benchmark and improve this particular isolated code etc. I was sure, that the code caused my performance drawbacks. Now I think, that the new rules (?) or rather the rules duplication (?) are to blame.

I will keep you informed if I will find something. Regards. Ivan

**Comment by guwirth** [comment]
@ivangalkin @ericlemes 
I merged #1503 you can download v1.1 from here:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

**Comment by ericlemes** [comment]
@ivangalkin, I think it is important first to pin down the problem. If it is the new metrics, we definitely can either improve or make them optional (run only if a particular property is set). I guess if we are comparing an analysis that computes lines of code with another that does not, it won't be a fair comparison.

But I just want to make sure when you did your benchmarks you are comparing the right things: cache with no-cache and if you are having enough memory to run the analysis.  This can make a significant difference.

**Comment by ericlemes** [comment]
@ivangalkin I don't remember now the details of the code, but the complexity metrics probably can be cached as well.

**Comment by ivangalkin** [comment]
@ericlemes thank you for the information: there is a couple of tasks, I've identified w.r.t. the complexity.

E.g. #1494 - I've started to implement the detailed warnings for the complexity issues ( `{  COMPLEXITY,  COGNITIVE_COMPLEXITY} x { function scope, class scope, file scope }` ). It requires the splitting between the metric calculation and the logic for the warning itself. So maybe caching makes sense here too.

**Comment by guwirth** [comment]
@ivangalkin I did a test on our test server:

SQ | CXX plugin | duration
-- | -- | --
SQ 6.7 |  0.9.9 | 28 min
SQ 6.7 | 1.0.0 | 26 min
SQ 6.7 | 1.1.0 | 26 min

See no performance decrease in our setup

**Comment by ivangalkin** [comment]
@guwirth I am glad, that I was wrong. Sorry for the false alarm and thank you for the measurement.

**Comment by guwirth** [comment]
V1.1 released
