### ISSUE TITLE
Not able to force plugin to find files from coverage report

### ISSUE THREAD

**Issue by kpiekara** [SonarOpenCommunity/sonar-cxx#1508]
### Description

Sonar Qube/Plugin is not able to find files which are described in converagexml.

```
DEBUG: Coverage BaseDir 'E:\sonarqube\sources\proj' 
DEBUG: Normalized report includes to '[E:\sonarqube\coverage\*.coveragexml]'
INFO: Scanner found '10' report files
INFO: Parser will parse '10' report files
DEBUG: Cannot find the file 'e:\sonarqube\sources\proj\file.cpp', ignoring coverage measures
```

Last message is presented many, many times. Maybe 3-4 times apear something like:
```DEBUG:` Saving '7' coverage measures for file 'e:\sonarqube\sources\proj\file.h'```

### Steps to reproduce the problem
```
Run SonarQube Scanner for MSBuild - Begin
Build all projects
Run unitests (codecoverage.exe collect, codecoverage.exe analyse)
Run SonarQube Scanner for MSBuild - End
```

### Expected behavior
SonarQube is able to find files and show coverage.

### Actual behavior
No coverage detected (something about ~0.1%)

### Related information
SQ: Version 6.7 

### Questions
Why there is problem with paths? BaseDir and paths to files with coverage are absolute and can be opened using explorer. I tried to capitalize paths like on the drive (I don't know why they are lowercased in report) but without effect.

Probably I don't understand something. What logic is used to decide if path if found or not? Because existing on hard drive seems to be not enough. 

I need to use MSBuild for SonarQube because I also have C# projects (so far not included into build).

**Comment by ivangalkin** [comment]
Hi @kpiekara,

just a short remark: if you use a [multi-module project](https://docs.sonarqube.org/display/SCAN/Advanced+SonarQube+Scanner+Usages), the appearance of the messages like `Cannot find file X, ignoring coverage measures` (as well as duplicate messages in general) are normal. The reason for such behavior is that the coverage sensor (or cppcheck, valgrind or each import-any-external-report sensor) is executed for each module separately.

* Imagine there is an external [coverage] report for files A1, A2, B1, B2, C1, C2.
* Sensor becomes executed for module A (contains files A1, A2) -> files B1, B2, C1, C2 cause the warning `Cannot find file {B1|B2|C1|C2}, ignoring coverage measures`. Obviously these files are missing in the module A. That's why the sensor warns you about it. 
* Sensor becomes executed for module B (contains files B1, B2) -> files A1, A2, C1, C2 cause the warning etc.

@kpiekara, do you have multi-module project?

Now to the low coverage: Which coverage format do you use? Are you able to verify, that the required paths are listed in the coverage files? Could you please provide a [full DEBUG log](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information), examples of the coverage files and maybe the details of your project structure? That would help analyzing the problem. Thank you!

**Comment by kpiekara** [comment]
Thank you for your respond. I don't use modules but it seems that MSBuild for Sonar is doing it for me. 

Now I see that these messages (`ignoring coverage measures`) are ok, so I tried once again with fixed paths to proper capitalization (don't know why codecoverage.exe is lowercasing them) and treat analyse like it would using modules. Now I' able to see coverage in sonar.

Big thanks for helping.
