### ISSUE TITLE
Custom rules limited to 4000 chars

### ISSUE THREAD

**Issue by gerboengels** [SonarOpenCommunity/sonar-cxx#1548]
Since SonarQube 7.0, there is a limit on the length of configuration settings. In our case, we use some XML in "Administration > C++ (Community) > Clang-Tidy custom rules" which exceeds the (new) limit of 4000 characters. Before SonarQube 7.0 this limit did not exist.

I think the regression was introduced in [this SonarQube commit](https://github.com/SonarSource/sonarqube/commit/e9de4d178493dc10e411e9135159319e8e6873cb#diff-00b336cdea1cc5c1c7d29cb5578550e8), for [feature 10040](https://jira.sonarsource.com/browse/SONAR-10040).

I don't know whether the cxx plugin can work around the issue, or if it should be fixed in SonarQube?

cxx plugin version: 1.0.0
Current SonarQube version: 7.2.0.13530

**Comment by guwirth** [comment]
Hi @gerboengels,

> "Administration > C++ (Community) > Clang-Tidy custom rules" which exceeds the (new) limit of 4000 characters. 

thanks for this hint. Think we can't workaround this because seems to be an SQ core issue. Like to ask you to create an issue in the SQ community: https://community.sonarsource.com/

Regards,

**Comment by jmecosta** [comment]
@gerboengels how have you find this? We have some big xml filea also but we
havent notice any crashes or anytbing

**Comment by yachoor** [comment]
@jmecosta Did you try editing Clang-Tidy custom rules through SonarQube UI in latest release?
It seems the limit only exists in UI validation (Validation failed. 'value' length (15617) is longer than the maximum authorized (4000)).
As a workaround I edit it directly in database

**Comment by gerboengels** [comment]
@jmecosta I found this after upgrading SQ from 6.x to 7.2, and then trying to modify the mentioned field. When clicking on save, the UI says it cannot be saved. But no crashes or anything.

**Comment by gerboengels** [comment]
@yachoor Will try editing the database directly

**Comment by jmecosta** [comment]
@yachoor ok, we dont have probelms since we are only using the custom rules place holder and those do not face this issue. and to be honest that one will stop working at some point since its the same type of variable however its a multivalue property and for some reason there is not check on that in the ui. Supose db has not limitations.

https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java#L301

that said:

@guwirth, @Bertk due to this newly introduced limitation. we can have 2 ooptions, 

1, drop this support. and let users create the rules using rest api. I do this all the time.
2. convert all those into multi values and then users can split those into files of 4k characters or less. 

what would be the best solution?

**Comment by guwirth** [comment]
> 1, drop this support. and let users create the rules using rest api. I do this all the time.

@jmecosta independent which way we are going: could you describe how it works with the REST API? Which commands are you using?

> 2. convert all those into multi values and then users can split those into files of 4k characters or less.

Don't know if this is a good idea. Have the feeling the configuration interface is already too big.

**Comment by jmecosta** [comment]
would be something like this:
for each repo we create a template rule: https://github.com/jmecsoftware/sonarqube-roslyn-plugin/blob/master/sonar-roslyn-plugin/src/main/java/org/sonar/plugins/roslyn/RulesDefinitionCSharpRoslyn.java 

the user can straight away create new rules based on this template rule. since this would be really a big work then you can use the "/api/rules/create" to post a new rule. how users use the rest end point its up to them, im using a f# library  see
 https://github.com/TrimbleSolutionsCorporation/VSSonarQubeExtension/blob/master/SonarRestService/SonarRestService.fs#L741

this would solve the current problem. however its a bit more work for end users.

**Comment by yachoor** [comment]
Last time I checked it did not allow to create rules with keys containing '-'. Before there was clang-tidy support I used to pass it's output as gcc with template rules, but I had to replace every '-' with '_' when creating rule from template and than fix it manually in database.

**Comment by guwirth** [comment]
SQ will add an API to relating external rule info https://jira.sonarsource.com/browse/MMF-1332. Maybe that is an solution?
