### ISSUE TITLE
Documentation on setting up clang-tidy is missing

### ISSUE THREAD

**Issue by sigiesec** [SonarOpenCommunity/sonar-cxx#1560]
There is no documentation on how to set up clang-tidy to support this. The relevant configuration properties are not even mentioned under https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties

The https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/samples/SampleProject2 also does not show how to do this.

**Comment by sigiesec** [comment]
One particular aspect that is unclear to me is how to extend the set for custom clang-tidy rules. Recently, a tool has been added to convert the clang-tidy documentation to an XML configuration file for SonarQube. I executed this on our custom clang-tidy fork based on clang(-tidy) 7.0.0, and it seemed to produce a valid output, but it is unclear to me how to deploy this.

**Comment by sigiesec** [comment]
Also, the generated rule database does not appear to include the compiler warnings aka clang-diagnostics-* rules from clang-tidy. How are these supposed to be handled?

**Comment by sigiesec** [comment]
Another aspect that is not clear to me: How are undefined rules handled? Does this result in an error or warning in the sensor or on the server? Or are they silently dropped?

**Comment by ivangalkin** [comment]
Hello @sigiesec,

I'll try to answer at least some of your questions:

1. The documentation is missing. That's true. All our sensors for import of 3rd party reports work like that:
* execute 3rd party analyzer (TOOL) and store the generated report under `<path>` (in other words - read documentation for the TOOL)
* make sure you've activated the quality rules for the TOOL (see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules). For clang-tidy the rule's repository is called `Clang-Tidy`
* set the property `sonar.cxx.TOOL.reportPath=<path>` (for clang-tidy it's `sonar.cxx.clangtidy.reportPath`) and execute the sonar-scanner (in other words - read documentation of sonar-scanner, mvn/gradle plugin etc)

We definitely have to update the documentation, but I'm afraid it won't be much more than this.

2. We've are about to update the rules for clang-tidy (#1558 is still not merged yet). So you have to use the 1.2.0-SNAPSHOT in order to have clang[-tidy] 8.0.0 support (snapshot build can be found here https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts).

3. The previous update of the clang-tidy rule-set was made for the version 6.x.x. That means we didn't update the rules between 6.x.x and 8.0.0. If some issue-ids for the version 7.0.0 are included neither in the 6.x.x nor in 8.0.0 the corresponding issues won't be imported
This is a general strategy of sonar-cxx's import: if issue-id is unknown - we ignore the issue and write a log

@guwirth I was thinking about introduction of `cxx.cppcheck.uncategorized`, `cxx.clang-tidy.uncategorized` and other `cxx.TOOL.uncategorized` rules. They could be used in order not to loose the issues with unknown issue-ids. What do you think?

4. Same logic is applied to the custom TOOL's rules: if ids are unknown to the default rule-set, they won't be imported to SonarQube DB / UI. **But** for each TOOL  sonar-cxx provides a parameter `sonar.cxx.TOOL.customRules=<xml data>` ( for clang-tidy it's `sonar.cxx.clangtidy.customRules`), which can be used in order to create of a custom rule-set. Please see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis for more info.

If you have more questions, please don't hesitate to ask.
Reagards,

**Comment by sigiesec** [comment]
@ivangalkin Thanks a lot for your answers. I figured point no. 1 out in the meantime myself.

I also read about no. 2 and #1558, but it was not clear to me that (point 3) the rules of 1.1.0 were as old as clang 6, which is quite unfortunate. Can you say when #1558 is going to be merged and sonar-cxx 1.2.0 released?

I think *.uncategorized rules would be a very good idea (it might be made configurable in the sensor whether they should be populated). This way, it would be much easier to identify an incomplete/outdated rule set, and still be able to somehow handle such rule violations at least in a limited way.

For 4: When I use the clangtidy_createrules.py to create an XML file, it will contain both the standard clang rules as well as our custom rules. Can I simply submit the whole XML file as customRules? What will happen to the duplicate rules then?

An open question from above is still the handling of clang-diagnostics-* rules, which correspond to compiler warnings. There is no documentation for them as part of clang-tidy, so clangtidy_createrules.py does not create rule definitions for them. How would I import these into SonarQube?

**Comment by sigiesec** [comment]
Hm, I just tried to use -Dsonar.cxx.clangtidy.customRules=clangtidy-rules.xml (where clangtidy-rules.xml was created using clangtidy_createrules.py), but it does not appear to have any effect. There is also no message in the output of sonar-scanner mentioning "clangtidy.customRules" or "clangtidy-rules.xml", even though I run it with -X

Any idea what I am doing wrong?

**Comment by GerrietReents** [comment]
> For 4: When I use the clangtidy_createrules.py to create an XML file, it will contain both the standard clang rules as well as our custom rules. Can I simply submit the whole XML file as customRules? What will happen to the duplicate rules then?

At the moment with SonarQube 6.7.5 and sonar-cxx 1.1.0 duplicate rules will prevent SonarQube from starting. You will have to remove the  `sonar.cxx.clangtidy.customRule` parameter from the database manually.

**Comment by ivangalkin** [comment]
Hi @sigiesec 

1. the `clangtidy.customRules` is meant to be used like 

```properties
#server-side properties file (/opt/sonar/conf/sonar.properties)
sonar.cxx.clangtidy.customRule=<?xml version="1.0" encoding="UTF-8"?><rules><rule> <key>custom-rule-key</key><name>custom-rule-name</name><description><![CDATA[ <h1>my description</h1>]]></description><severity>MINOR</severity><type>CODE_SMELL</type>/rule></rules>

```

... which is a single-line squashed XML data, describing your rule-set file. Please keep in mind that you can enter the same data from the configuration UI, but there is a length limitation (please read the details and the workarounds in #1548)

Please create the XML data manually. ID duplications are not allowed.

2. sonar-cxx supports the import of clang static diagnostics (aka clang -analyze). Please take a look at the rules collected in Clang-SA repository (https://<sonar>/coding_rules) and enable them if interested. Than you can import the reports as described in https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers (grep for `clang` please). 

We support parsing of gcc and ms-vc compiler logs. They are analyzed through regular expressions and known warnings become imported to SonarQube (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers). This feature is missing for clang compiler logs. Please double check if it is maybe covered by "clang static analyzer".

3. I would like to forward all questions about the plugin release to @guwirth. Thx!

**Comment by sigiesec** [comment]
> Please create the XML data manually. ID duplications are not allowed.

Hm, it would be nice if this limitation would be lifted, and I could directly use the output from clangtidy_createrules.py. It would be fine if rules with duplicate IDs would be ignored here.

> This feature is missing for clang compiler logs.

Well, that's not exactly what I was talking about. The clang compiler itself reports warnings such as -Wunused-variable, but clang-tidy has corresponding diagnostics (such as clang-diagnostics-unused-variable in this case). The output format is very similar though (if not identical).

But the main challenge here is that the list of warnings would need to be converted to rule definitions again. In the source code, they are defined here: https://github.com/llvm-mirror/clang/blob/11fd5cf9fd813938a0d3140fb878851c22d67a65/include/clang/Basic/DiagnosticGroups.td, and there is documentation here: http://clang.llvm.org/docs/DiagnosticsReference.html, I am not sure if there is some source rst file for this that could be parsed in the same way as the clang-tidy rules definitions.

> Please double check if it is maybe covered by "clang static analyzer". 

No, the clang-static-analyzer rules have some overlap with clang-tidy, but these are the clang-analyzer-* rules of clang-tidy.

**Comment by sigiesec** [comment]
> Is there a way to see the list of all clang-tidy diagnostics (especially the ones, which are derived from compiler warnings?) 

Unfortunately not. You can get the list of diagnostics by running
`clang-tidy checks="*" -list-checks` but this specifically does not include the ones derived from compiler warnings.

> If there is no reliable solution (like CLI switch, parsable documentation or such) we can parse the source code too (DiagnosticGroups.td). 

I fear there is no other option. This was also suggested here: https://stackoverflow.com/a/32326662/2019765

> @sigiesec you can always contribute, since you seem to have a large experience with clang-tidy.

I can try :) I have some experience with clang-tidy, but unfortunately not with SonarQube and the sonar-cxx plugin (yet), so there is some learning curve on that side ;)

> I would rename this issue to the feature request (US) like "US: clang-tidy: update rules with compiler diagnostics"

That already exists as #1536 

> I would suggest to open a new issue like "US: CxxIssuesReportSensor: don't ignore rules with non-existing rule-ID; enable fallback to the sensor-specific "uncategorized" ID"

Sounds good!

**Comment by guwirth** [comment]
> I was thinking about introduction of cxx.cppcheck.uncategorized, cxx.clang-tidy.uncategorized

In case of an undefined message key you get already today a warning in the LOG file. To fix this an update of the plugin or setting .customRule is necessary.

> .customRule

not sure if there is a future for .customRule because of #1548

> RulesDefinitionXmlLoader

Is also marked as deprecated. Replacement open?

SonarSource introduced an API to forward messages from 3rd party tools. They also like to add an API to relating external rule info https://jira.sonarsource.com/browse/MMF-1332.

I like to wait in which direction everything is going before bigger changes.

**Comment by ivangalkin** [comment]
> In case of an undefined message key you get already today a warning in the LOG file. To fix this an update of the plugin or setting .customRule is necessary.

@guwirth in my opinion we have a very verbose LOG (flooded by missing-include warnings for example). So writing something to the LOG doesn't rise the appropriate attention. Having some "uncategorized" findings with a description...

```
ID is not part of standard rule set; please open an issue at https://github.com/SonarOpenCommunity/sonar-cxx/issues; Please see http://www.TOOL.com for warning description
```

... 1) wouldn't hide (maybe very important) findings, 2) would rise more attention to missing rules and 3) (ideally) would improve our sensor support.

ALSO

@sigiesec @guwirth I volunteer to implement the support for desired clang-tidy warnings (the one derived from clang compiler warnings and described in https://github.com/llvm-mirror/clang/blob/11fd5cf9fd813938a0d3140fb878851c22d67a65/include/clang/Basic/DiagnosticGroups.td). I suggest a quick (and dirty) implementation in order to be in time for next release. Instead of a detailed rule description I suggest to use a reference to http://clang.llvm.org/docs/DiagnosticsReference.html at least for the first time. We use a similar minimalist rule descriptions in [clangsa.xml](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/clangsa.xml). Later we could extend the description by more advanced parsing. But for the first time we would solve the swallowing of important warnings.

Do you agree?

**Comment by sigiesec** [comment]
@ivangalkin Sounds very good! Thanks a lot!

> So writing something to the LOG doesn't rise the appropriate attention.

Yes, and this would only be visible to someone looking deep into the log, which will typically run on some CI server, whereas the Sonar UI might be used by more/all developers. This may be undesired in some settings, but they can simply deactivate the uncategorized rule.

**Comment by guwirth** [comment]
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.clangtidy.reportPaths
