### ISSUE TITLE
Ant-style path patterns for include directories

### ISSUE THREAD

**Issue by GOMSPACEMartin** [SonarOpenCommunity/sonar-cxx#1561]
Quick question ...

Is it possible to use an ant-style path pattern for the include properties in SonarQube?

I have headerfiles in a folder structure that goes something like this:

/lib_abc/123/module1/bleh/include
/lib_abc/component2/include
/include
/lcomponent3/module4/include

What I want to do is include all these headerfiles with a **/include kind of style as the directories might change depending on the project - but I do not want to setup every time ... problem is that it does not seem to work :/

Trying to avoid issues like ... "Unable to find the source for '#include <lib/util/module/header.h>"

thanx.

**Comment by ivangalkin** [comment]
Hi @GOMSPACEMartin and thank you for reaching out.

currently all include paths must be passed as is, without any wildcards or placeholders. You can compare it with GCC invocation (`-I<include path0> -I<include path1>` etc).

Creating an ant-style path is a feature request. Before we discuss it, I would suggest you to use the following alternatives:

a. You can intercept your build by [Bear](https://github.com/rizsotto/Bear) and use the resulting JSON compiler database for the passing of all paths and defines. Please see `sonar.cxx.jsonCompilationDatabase` (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties) . Some build systems (e.g. cmake) are able to generate the compiler database out of the box. It's more convenient than passing all headers/defines manually.
b. You to ignore the warnings à la "missing includes" completely. They do not play any role at all if you import static analysis reports from 3rd party tools. They might have very limited impact on the size/complexity metrics or internal checks, but 

*    you are most probably interested in the dynamic of the metrics (is there fall/rise off some metric) rather then in its absolute value
*    we suggest to use external static analysis tools instead of internal checks anyway

For the list of external tools we support please see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-tools

**Comment by guwirth** [comment]
@GOMSPACEMartin think it's not possible to use a pattern for includes. To get the right results you need an **ordered list** of includes. The order for a static code analyser have to be the same as in your build environment. To understand this better google for #include and how a preprocessor is doing this. 

Other way is as recommended from @ivangalkin to ignore the #includes and add some syntax sugar to reduce the number of syntax error in case of unknown data types: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

**Comment by GOMSPACEMartin** [comment]
currently investigating what can be done with GCC, not sure I can find any references to **ordered list**'s

ignoring the includes may be an option, but I have observed code smells increase when adding an include directory, need to look more into that.

interceptions like bear is not feasible due to our build/ci setup
