### ISSUE TITLE
Any example code for rule "Avoid usage of the function"

### ISSUE THREAD

**Issue by salomon1184** [SonarOpenCommunity/sonar-cxx#1573]
I'd like to add rules to forbid use some functions, is there any example code for this? thank you.

**Comment by ivangalkin** [comment]
Hello @salomon1184 and thank you for reaching out!

I would prefer to use cppcheck for that purpose. It allows to create custom rules, which will warn about usage of unwanted functions. I've created a detailed how-to under

https://github.com/ivangalkin/sonar-cxx-custom-cppcheck-example

Please check it out. Best regards.

**Comment by salomon1184** [comment]
@ivangalkin thanks for your reply， I have seen the cppcheck way，but feels it too complicated， is there any possible to create custom checks using sonar-cxx lint ？ 

thanks again. Best regards

**Comment by ivangalkin** [comment]
Hi @salomon1184 

>  I have seen the cppcheck way，but feels it too complicated

### cppcheck:

1. yes, there are some additional initial steps in order to create custom rules and to activate them. Afterwards you just need to execute the cppcheck each time before the actual sonar scan. This works well for the scans, which are integrated into some CI chain. I agree, that it might not very convenient for manual/local execution.

2. You might want to create a [git hook](https://github.com/danmar/cppcheck/blob/master/tools/git-pre-commit-cppcheck), which executes the cppcheck e.g. while pre-commit phase. This would be a kind of semi-automatic solution. 

**Pros**: cppcheck has a good parser, which allows the rules like "forbidden function" be written very easily
**Cons**: cppcheck is an external tool and you have to run it separately before the actual SonarQube scan

> is there any possible to create custom checks using sonar-cxx lint ？

There are at least 2 build-in solutions, which sonar-cxx supports out of the box

### XPath rules (rule `cxx:XPath`)

XPath is a mighty [query language](https://www.w3.org/TR/2017/REC-xpath-31-20170321/), which can be applied among others to the abstract syntax tree (AST) of the parsed program. You can create a custom rule and identify all AST nodes, which match (or do not match) some XPath query.

Obviously in order to write such rules one have to know the formal C/C++ grammar in general and our parser implementation in particular. E.g. function invocations are represented by so called "postfix expressions", the actual function name might or might not have a namespace or template arguments etc. So writing the precise query might be a bit tricky.

Below I'll show an example how to react on some generic identifier. It's not really accurate, but still a working solution e.g. in order to detect some simple "forbidden functions". Since we don't query for postfix expressions, but for generic identifiers there could be false positives.

**Pros**: built-in solution, benefits from C/C++ parser
**Cons**: writing of precise query requires the knowledge of XPath, C++ grammar and sonar-cxx internals  

###  RegExp rules (rules `cxx:FileRegularExpression`, `cxx:LineRegularExpression` and maybe `cxx:CommentRegularExpression`)

Regular expressions doesn't benefit from the parser. While XPath queries use a parsed AST, regular expressions treat the source code as a plain text. E.g. there is no distinguishing between the real source code from the comments.

It is still possible to write a regular expression, which will match the call of some "forbidden function". You'll definitely find some examples on the internet. For some simple function names this might work well. Mastering templates and namespaces with a regular expression could be very challenging.

**Pros**: built-in solution
**Cons**: same drawbacks as by XPath: as soon as the name of "forbidden function" becomes complex you'll need to master the syntax of C++

### XPath Example
(RegExp example will be similar, but you should figure the query by yourself)

We'll write a XPath query which detects a presence of identifier "printf" in the source code. Comments are ignored. Type of identifier is not restricted, so false positives are possible. Please take a look at our [implementation of the C++ grammar](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java) in order to make the check more accurate. 

1. Find the rule `cxx:XPath` (`c:XPath` if you use C plugin) and create a custom rule

![cxx_xpath_0](https://user-images.githubusercontent.com/11503715/47017843-9fe6e480-d153-11e8-8c44-b9a65887ae3d.png)

2. Write a XPath query (e.g. `//IDENTIFIER[@tokenValue = "printf"]`) and save the new rule

![cxx_xpath_1](https://user-images.githubusercontent.com/11503715/47017912-c3119400-d153-11e8-8982-4ae9305528d1.png)


3. Activate this rule in your quality profile (your project must be associated with this quality profile)

![cxx_xpath_2](https://user-images.githubusercontent.com/11503715/47017865-aa08e300-d153-11e8-9b71-4b770330bd5d.png)

4. Perform the scan

![cxx_xpath_3](https://user-images.githubusercontent.com/11503715/47017919-c7d64800-d153-11e8-8975-de3a3e5adad0.png)

**Comment by guwirth** [comment]
@salomon1184 as @ivangalkin was saying build-in is Regex and XPath. I would also prefer using an external tool. Here you are long term on the safe side. Especially with Xpath I don’t know how the future looks like? SonarSource already removed it from some of their plug-ins.
