### ISSUE TITLE
Code contains FlatBuffers items stuck forever

### ISSUE THREAD

**Issue by herozabbix** [SonarOpenCommunity/sonar-cxx#2052]
### Description
My project uses Sonar-CXX plugin to scan C ++ projects, and everything was working well, but after a flatbuffers-related function was submitted, our scan was stuck all the time. Using Debug to check the scanning process, we found that we were stuck in several files (.cpp,.h), which referenced a lot of code of flatbuffers-related functions

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Prepare the SONAR-CXX scanning environment

2. Scan an item that contains the FlatBuffers function. Scan by adding the -x parameter. During the scanning process, it will always be stuck on some files that reference the FlatBuffers

### Expected behavior

Sonar-CXX runs normally with projects that contain Flatbuffers related functionality

### Actual behavior

Sonar-CXX has been stuck on the file containing the FlatBuffers function during the scanning process, without any error report and useful information

### Known workarounds

We can't solve the problem, we can only eliminate the stuck files

### LOG file
```
[root@test project]# sonar-scanner -Dsonar.host.url=xxx -Dsonar.sourceEncoding=UTF-8 -Dsonar.login=xxx -Dsonar.password=xxx  -Dsonar.projectKey=xxx -Dsonar.projectName=xxx -Dsonar.projectVersion=xxx -Dsonar.sources=./source  -X
......
18:35:44.995 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:6]: cannot find include file '#include "layerexport.h"'
18:35:44.995 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:7]: cannot find include file '#include "generated.h"'
18:35:44.995 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:8]: cannot find include file '#include "rect.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:9]: cannot find include file '#include "guideline.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:10]: cannot find include file '#include "star.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:11]: cannot find include file '#include "triang.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:12]: cannot find include file '#include "group.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:13]: cannot find include file '#include "text.h"'
18:35:44.996 DEBUG: [xxx/fb/core/changeset/changecollection.cpp:14]: cannot find include file '#include "skpath.h"'
```
And it's stuck here forever! 
### Related information

* cxx plugin version?
1.3.2
* SonarQube version?
7.9.2-community

**Comment by guwirth** [comment]
Hello @herozabbix,

thanks for the feedback. Currently I'm only aware of #1685 (nested templates and a lot of `>>>>`) which could lead to such an effect.

- Did you try to get debug information (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information)? Any other information in the LOG file?
- Other hint: It is typically not necessary to read all include files. The CXX plugin is doing only a syntax analysis. It is often better to provide some syntax sugar instead of all include files (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces). You can also try with `includeDirectories=.` only.
- Is the execution really hanging? In case you know the file you can play around with the sslr-toolkit to narrow down the problem (https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-1.3.2/sslr-cxx-toolkit-1.3.2.1853.jar). Copy the code into the tool and verify if it is working there. Remove parts and try again...
- Could you provide a sample file?

Regards,

**Comment by herozabbix** [comment]
like this: https://github.com/SonarOpenCommunity/sonar-cxx/issues/1916

**Comment by guwirth** [comment]
@herozabbix we will try to solve this as part of the 2.0 version.
