### ISSUE TITLE
Can I use Sonar-cxx plugin to scan both C and C++ in a project

### ISSUE THREAD

**Issue by thanhngo91** [SonarOpenCommunity/sonar-cxx#2288]
Hi all,

Actually I installed Sonar-cxx plugin and after that I tried to scan for .C and .CPP by add both extension to suffixes field.
But I checked result and I saw that scanner apply some C++ naming convention for source code in .C 
So could you let me know how to limit rule for C and C++ separately
Because I saw that in older version the plugin support C (community) and C+ (community) .

Thank you,

**Comment by guwirth** [comment]
Hi @thanhngo91,

in the past we had two plugins, one for c and one for c++. The 2.x cxx plugin is one plugin using a C++ grammar (with some extensions). It’s no more possible to differentiate between different languages (it’s all one language cxx now).
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes

> So could you let me know how to limit rule for C and C++ separately

That’s no more possible. Because main intension of the plugin is to use external reports you have to configure the external tools accordingly. cxx internal roles are always valid for all listed file extensions.

Regards,

**Comment by FSOFT-THANHND21** [comment]
Hi @guwirth 

Many thank for your clear feedback. It help me a lot.

Regards,

**Comment by thanhngo91** [comment]
Hi @guwirth 

Thank for your clear feedback that help me a lot.

Regards
