### ISSUE TITLE
Cxx community plugin sonar scan analysis taking too long to complete

### ISSUE THREAD

**Issue by fayaz988** [SonarOpenCommunity/sonar-cxx#2495]
Run sensors on project
INFO: Sensor CXX [cxx]

ERROR: unsupported declarator at 6559
ERROR: unsupported declarator at 6561
ERROR: unsupported declarator at 6523
ERROR: unsupported declarator at 6525
ERROR: preprocessor: undefined function-like macro 'defined' assuming 0
ERROR: unsupported declarator at 688
ERROR: unsupported declarator at 689
ERROR: unsupported declarator at 690
ERROR: unsupported declarator at 691
ERROR: unsupported declarator at 692
ERROR: unsupported declarator at 693

after cpp report xml generation Run sensors for C++ project taking long time to complete analysis.

**Comment by guwirth** [comment]
Hi @fayaz988,

thanks for your feedback!

Difficult to say what the issue is with this small LOG snippet. Seems that the parser runs into a syntax error. That’s most likely because of missing macro:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

Please turn debug info on to get more details:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Regards,

**Comment by guwirth** [comment]
@fayaz988 please reopen if still an issue
