### ISSUE TITLE
The art of parsing

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#272]
In the past we had already the discussion about the right way of 'error recovery' in the C++ plugin. In one of the discussion on the SonarQube community mailing list Dinesh Bolkensteyn stated:

*Our previous approach with the C++ plugin was also to implement some recoveries, but we failed, and then changed our strategy. For more details on our new approach, you'll want to watch "The Art Of Parsing"* (http://sonarqube.15.x6.nabble.com/sonar-dev-SSLR-and-Error-Recovery-tt5020231.html#a5024335)

Now I found a link to the presentation, but still don't know what this means for the community plugin?

**The Art Of Parsing**
http://de.slideshare.net/dbolkensteyn/the-art-of-parsing-devoxx-france-2014
Conclusion in this slides:
* PEG: dead-end for C/C++
* GLL: the only clean choice for C/C++

**Comment by LegalizeAdulthood** [comment]
I'm late to this thread only recently having discovered SonarQube, but I am very familiar with what is going on in the clang world and honestly, you really should use Clang to do all the parsing into an AST.  It's not just some secondary library it is the same code used by the compiler and it is **designed** to be used as a library for exactly this purpose.

I just tried running the community plugin on one of our source bases and it keeps complaining about not being able to analyze certain files.  These are all files where they are (ab)using the preprocessor to supply syntactic boiler plate around some construct.  These files are perfectly valid syntactically once they go through preprocessor expansion, but because the community plugin doesn't completely and faithfully implement the same things as a real compiler, the tool is having a hard time.

**Comment by wenns** [comment]
Thanks for your opinion. Maybe we should go that way. *If* we would, I expect the parsing and getting an AST out of clang be the easier part of the job. The harder part would be adapting the stuff, making it a SSLR drop-in replacement, and **maintaining** it to be a SSLR drop-in replacement. And I think it would be wise to go this way, as doing so we would (still) be able to:
* port the checks from other languages in a straightforward manner
* profit from common libraries
* have an SQ'isch look & feel
* ...
Staying close to the other mainstream plugins enables pretty efficient maintaining of the code base. I think thats very important in the long run, as SQ evolves very rapidly and we've limited resources.

**Comment by guwirth** [comment]
Hello Richard, can you provide us some examples were you have problems with the preprocessor please. 

Von meinem iPhone gesendet

**Comment by LegalizeAdulthood** [comment]
I opened a bug report on one of them with a NullPointerException.  It's a closed source project, so I can't share the actual source.  I can say that I'm able to run cppcheck succesfully on the code.  I'm not sure I understand everything that's going on in SonarQube yet to understand how hard or easy it is to wire in a clang-based parser.  I'm still learning SQ and how to best use that for our projects.  I tried using the configuration option to skip past parsing errors, but it didn't help.

**Comment by guwirth** [comment]
clang: Problem in the past was that clang was not supporting GCC and VS extensions of the. Still don't know how good they are here.
There is also a big difference between a compiler which should be as correct as possible and a analyzer like the plugin which should be as tolerant as possible.
Currently my feeling is that the biggest problems in V0.9.2 are #49 and #226. After closing this most should work.
So still seeing pros and cons for changing the parser.

**Comment by jmecosta** [comment]
the good thing about adopting clang would be the less maintenance from the
plugin side. on top that you get support to new c++ standard for free
(c++14 already included)... another advantage would be if putting a source
analyser based on clang with the current checks it might get the clang
community interested in improving this plugin....

**Comment by LegalizeAdulthood** [comment]
As far as I know, there are only two gcc extensions that clang doesn't support.  Honestly, I'm more concerned about basic parsing of valid ISO C++ source files and less concerned about parsing extensions specific to a compiler, but your priorities may be different.  I think their [compatibility page](http://clang.llvm.org/compatibility.html) describes what they support.

In the long run, clang is going to get better and better and have more people working on it than sonar-cxx.  From my perspective, the cons are diminishing and the pros are increasing.

@jmecosta There is substantial work going on in the clang community for creating source code checkers/fixers.  Most of this is focused around the static analyzer and clang-tidy, but standalone tools are also possible.

Right now I'm seeing lots of duplication of effort between this plugin, cppcheck, clang-tidy/clang static analyzer, and [oclint](http://oclint.org/).  cppcheck has gone pretty far with their approach, but it feels like clang's approach is going to win out in the long-run.  cppcheck suffers from ad-hoc inferencing and pattern matching and lack of a true semantic analysis of source code, leading to false positives.  They've gotten better over time, but I still have to sprinkle cppcheck-suppress comments around my code to get cppcheck running clean.  clang's static analyzer isn't perfect either, but so far I haven't had to suppress anything.  Maybe sprinkle around an occasional assert on a pointer because I know it's not nullptr at that location but clang couldn't figure it out.

**Comment by wenns** [comment]
I think we should try to go in this direction and try to replace the parsing backend with the clang-based one. It should be pretty clear by now, that we will *not* overcome the last hard parsing problems using the SSLR approach. The SonarSource guys made the same experience and use an other parsing technology now:

http://www.sonarqube.org/ccobjective-c-dark-past-bright-future/

Also, the preprocessor is still home-grown and would need a complete rewrite to get 100% standard compliant. 

As for pros and cons from users perspective, I thing the former overweight the latter by far. We *may* sacrifice support of *a few* VS extensions (or maybe not, see e.g. http://clang.llvm.org/docs/MSVCCompatibility.html) even if, it would be worth it.

Although the earlier experience in reusing an external parsing library (Eclipse CDT) were less than good, the fact that clang is designed to be reused may change the game.

So what has to be done to replace the SSLR-based parsing backend with the clang-based one, what subproblems have to be solved? At least the following, it seems:
- get java binding for libclang (google points to https://github.com/pkukielka/jclang ?)
- understand how and implement driving clang to parse the code
- get the resulting AST out of it
- implement an SSLR adaptor, which would turn this result in something cabable of serving as the basis for all the stuff, which is currently implemented on top of the SSLR-AST. This includes:
  1. the AST-based checks
  2. dependency analysis checks
  3. calculation of the documentation metrics
  4. calculation of cyclomatic complexity metrics
  5. the size metrics (ncloc, statements, functions, classes...)
  6. ??
- adapt this functionality to run on the new AST (necessary, because at least the names of the nodes will change du to an other grammar)

Looks like a couple of weeks of fun ;) Too bad I cannot afford the time.

The good thing is, we have integration tests in place which would guard us against most regressions.

**Comment by LegalizeAdulthood** [comment]
Personally, I think it is placing the interface too low to put a java interface on the AST.  IMO, the entirety of the rule checks should be on the C++ side.

I've been writing additional checkers/fixers for [`clang-tidy`](http://clang.llvm.org/extra/clang-tidy.html) and it is **so much easier** to write these in C++ than it would be to marshall all this crap over to Java and write the check there.

IMO, what you want to do is hand off the analysis to something like `clang-tidy` or the [clang static analyzer](http://clang-analyzer.llvm.org/) and simply ingest the report from these tools.  Heck, you're already duplicating effort with clang's static analyzer, clang-tidy and [oclint](http://oclint.org/), why suffer from [NIH syndrome](http://en.wikipedia.org/wiki/Not_invented_here) when instead you can just run these tools and ingest the results.

The only thing that the community plugin is providing better than these other tools is the copy/paste detection, so focus on that and leverage the other tools to do what they do well.

**Comment by guwirth** [comment]
I'm with @LegalizeAdulthood. The complete tool to create the AST should be in C++. Means we are using the clang frontend and replace the backend to create a squid compatible AST. The cxx plugin is then only importing the syntax tree (AST). Only concerns I have is the number and size of intermediate files. Each source file will have an AST file on harddisk.

@LegalizeAdulthood: Do you have experience with this? How easy is it to reuse the clang frontend and write resulting syntax tree (AST) to a file?

Drawback of this solution is:
* plugin is splitted into c++ and java part
* we have to provide an additional command line tool, users of plugin have to install it

**Comment by jmecosta** [comment]
I agree with Richard. As we would just be duplicating stuff on both sides.
Moreover if moving everything to native we can reuse most of the stuff that
is already available, I mean the checks that are far more suitable then the
ones we have adapt from java. For example memory leak detection should
already be possible to do with clang. And something we dont have.

**Comment by wenns** [comment]
> Personally, I think it is placing the interface too low to put a java interface on the AST. IMO, the 
> entirety of the rule checks should be on the C++ side.

You guys didnt understand me correctly. Or I wasnt clear enough. Im **not** pleading for putting the focus on developing the checks in Java inside the plugin. The built-in-checks we currently have are nice-to-have *at most* and not strategically important. We dont put much effort in developing those; most of them exist just because the port from some other plugin was easy enough. Other people can do that (i.e. implement static code checking) much better anyways.

My point was that we have to turn the clang-AST in squid-compatible AST **for other reasons**, namely to be able to stack all the other code (including most of our metrics calculations) on top of it. And AFAICS, this is best (i.e. with least effort) done using Java bindings to libclang. If they're in decent shape and it works out.

> IMO, what you want to do is hand off the analysis to something like clang-tidy or the clang static 
> analyzer and simply ingest the report from these tools. Heck, you're already duplicating effort with 
> clang's static analyzer, clang-tidy and oclint, why suffer from NIH syndrome when instead you can 
> just run these tools and ingest the results.

Run tools and inject the results *we do*. Look at cppcheck, pclint, rats, ... As already said, the built-in checks are just another rule engine, which happens to be there. Ideally, static code checking support is tool agnostic anyways, but for historical and some technical reasons (first of all the rule repos, which are tied to particular tools) we have a number of sensors handling this use case. But this may change in future, when SQ core guys invent new ways of maintaining the rule metadata.

**Comment by jmecosta** [comment]
In which state the java bindings are? A quick look in google did not point
me to anything specific. By the way the dot ney plugin is implementing the
metrics also in native c# and roslyin. Maybe we can take some ideas from
there

**Comment by jmecosta** [comment]
and for code duplication detection. see 

https://github.com/SonarCommunity/sonar-csharp/blob/master/NSonarQubeAnalyzer/NSonarQubeAnalyzer/Metrics.cs

CopyPasteTokens, so dumps the tokens to file and reads it from java side.

on java side: https://github.com/SonarCommunity/sonar-csharp/blob/master/sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpCPDMapping.java

**Comment by guwirth** [comment]
> turn the clang-AST in squid-compatible AST

That is also what I tried to say with clang frontend and squid-compatible AST backend. However: write/read squid-compatible AST via a XML file, Java bindings to libclang, ...

Nevertheless I agree with @wenns that this is a bigger change taking a while. My gut feeling we will see no final solution here for the next 6 month.

**Comment by LegalizeAdulthood** [comment]
Dumping the AST into your own format is a matter of writing an AST visitor.  [This discussion on stackoverflow](http://stackoverflow.com/questions/5309405/can-i-get-an-xml-ast-dump-of-c-c-code-with-clang-without-using-the-compiler) may also be relevant.

**Comment by guwirth** [comment]
Found this in your link. Sounds not promising...

**Comment by LegalizeAdulthood** [comment]
Realistically, I am not interested in having sonar analyze the standard library headers.  When traversing the AST in clang you can identify the ultimate source of any single **token**.  Everything is attached to a source location that gives you file, line and column information for the start and end of a token, range of tokens, node in the AST, etc.

Most checks in clang-tidy ignore matching AST nodes that didn't originate in the current translation unit by using the `isExpansionInMainFile()` [narrowing matcher](http://clang.llvm.org/docs/LibASTMatchersReference.html#narrowing-matchers).  You can also narrow by whether or not the node is expanded from a system header or is in a regex matching the filename and you can always write your own custom code in the matcher callback itself if the narrowing matchers don't discriminate according to your specification.

**Comment by wenns** [comment]
> Dumping the AST into your own format is a matter of writing an AST visitor. This discussion on 
> stackoverflow may also be relevant.

Exactly. We dont want to fiddle with XML files or anything. libclang is a lib, and as a such, should not force you to use certain output channels. Ideally: we give it the source code in form of a string or a stream along with some context (include paths, options) and it outputs a tree of Java objects. Thats the deal.
The 'narrow matching' and excluding the vast amount of come coming from the external libs is of course an important sub-problem. Currently, this is done via our PP implementation, whose handling of an #include is not actually including the code, but recursively scanning the included code for macros.
