### ISSUE TITLE
sonar.cxx.cFilesPatterns => sonar.cxx.c.suffixes.sources

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#353]
Looking to #291 I'm not really happy with the solution. Wondering how we will provide a generic way to support c and cpp? Switching only __cplusplus macro seems to be also to less. At the end there will different includes, defines, tool chains, ...

One way could be to duplicate all settings, example

sonar.cxx.suffixes.sources => generic
sonar.cxx.c.suffixes.sources => for c only

sonar.cxx.defines => generic
sonar.cxx.c.defines => for c only, overrides sonar.cxx.defines for sonar.cxx.c.suffixes.sources

This solution could be used for all properties and is extendable in case of new variants. what are you thinking?

**Comment by wenns** [comment]
#291 contains a discussion about this feature. I think, the approach "C-compatibility mode switchable by file name extension" is pragmatic and acceptable, at least for the foreseeable future. The name of the property is not set in stone, though ;)

**Comment by guwirth** [comment]
Let's make an concrete example.

First the suffixes for 'different' configurations has to be defined
```
sonar.cxx.suffixes.sources=.cpp,.cxx
sonar.cxx.c.suffixes.sources=.c
```
Depending on suffix the plugin is using corresponding configuration
```
sonar.cxx.defines=...
sonar.cxx.c.defines=#define virtual __virtual \n\
                                    private __private
```

**Comment by guwirth** [comment]
Hello @Typz what are you thinking?

**Comment by wenns** [comment]
Well, lets talk about C ;)

I think we should discriminate between the (principal) approach, the implementation and the UI.

**Approach**
Right now, the plugin switches in C-compatibility mode when the file under analysis matches some configurable pattern. I think this approach has its advantages because it supports mixed C++/C projects, which are quite numerious. Pure C projects are supported also: just make sure that all files are considered by be 'C' ones.

**Implementation**
Current implementation of this mode just masks -- transparently -- the c++ keywords via the preprocessor, switches the cplusplus macro and (re)uses our C++ grammar, which already has a couple of tuneups to better swallow C-code. This is, of course, not ideal, (ideal would be a dedicated, standard-conform grammar) but already allows to deal with lots of C-code. I think it can be evolved to (or replaced with) something better in future releases without causing much churn.

**User Interface**
The only peace the user (currently) interacts with is this 'sonar.cxx.cFilesPatterns' property. I think Guenters proposal to provide a dedicated namespace for c-related configuration: "sonar.cxx.c" is a good one. If we go this way we should do the property rename before release. I also kind of like the 'sonar.cxx.c.defines' thing, because it allows for arbitrary c-specific transformations, and not only hardcoded keyword replacing. It causes work for every new user, though...



This will allow us to grow without affecting 


I think We can evolve that to something better without causing 




The current implementation of this mode 

A side note: the commercial SonarSource plugin supports C++, C and Objective C with one code base. Dont know how they do that. 

An alternative to this would be

**Comment by guwirth** [comment]
@Typz can wie change this? sonar.cxx.cFilesPatterns => sonar.cxx.c.suffixes.sources

**Comment by guwirth** [comment]
Close this because there is an own c plugin now (#1100)
