### ISSUE TITLE
Needs to support compile_commands.json

### ISSUE THREAD

**Issue by LegalizeAdulthood** [SonarOpenCommunity/sonar-cxx#421]
sonar-cxx only lets me configure macros and include paths at the project level.  This is an over-simplification of how things work in a C++ code base.

Instead, it should support [`compile_commands.json`](http://clang.llvm.org/docs/JSONCompilationDatabase.html) which allows me to define includes and preprocessor symbols appropriately for each and every file in my build.

**Comment by LegalizeAdulthood** [comment]
Oh, and this would come for free if you were based on clang libtooling.

**Comment by jmecosta** [comment]
How would you produce the compile commands file?

**Comment by LegalizeAdulthood** [comment]
CMake can generate it directly if you have a CMake-based build.  If you had a SCons based build you could generate it from SCons.

There are also approaches of providing a "build system interceptor" so that you run your build system and when it invokes the compiler, it's actually invoking your interceptor which captures the compile command for each translation unit before passing the command onto the real compiler.  Clang's static analyzer uses the latter approach, but only as a way of integrating the static analyzer into real-world builds that can't generate a `compile_commans.json` file.

**Comment by Typz** [comment]
The documentation recommends Bear https://github.com/rizsotto/Bear in case the file is not generated by cmake/scons.

-- 
Francois

**Comment by jmecosta** [comment]
Yes this is cool. We use msbuild, and ive created pull request to support a
similar approach see #399. Ive tough it would be a good idea to include
already something to use only macros and includes that are used in each
file. But that requires a bigger change. But I like the idea

**Comment by guwirth** [comment]
Are these tools especially Bears also running on Windows?

> Am 06.02.2015 um 20:44 schrieb Jorge Costa <notifications@github.com>:
> 
> Yes this is cool. We use msbuild, and ive created pull request to support a
> similar approach see #399. Ive tough it would be a good idea to include
> already something to use only macros and includes that are used in each
> file. But that requires a bigger change. But I like the idea
>

**Comment by jmecosta** [comment]
Should be quite portable in unix operating systems according to readme.
Anyway what it requires from the plugin side is the ability define includes
and macros per file. Once that is done we can have multiple parsers
supporting multiple operating systems

**Comment by LegalizeAdulthood** [comment]
Currently, there is no good solution for generating a `compile_commands.json` file from Windows.  The best I've been able to do so far is to extract compile commands from a full build log.  You can cobble this together by hand in an emergency.  A better approach would be a script that uses the VS automation interfaces to obtain the command-lines for every file in every project in a build configuration (Release, Debug, etc.).  Better still would be for CMake to generate a `compile_commands.json` file when using the VS project generators, but that isn't implemented.

**Comment by jmecosta** [comment]
What are the limitations of hacking the build log. As I see it is just
another parser. Or is there something missing from the log needed ?

**Comment by LegalizeAdulthood** [comment]
Besides the obvious limitation that screen scraping the build log is fragile, there is the issue that the build log only contains compile commands for things that were actually compiled.  If you don't compile, you don't have the log.  If you don't do a full recompile, then you don't have all the compile commands for all the translation units in your project.

IMO, it is more work to parse the build log than it is to use the automation API to walk the project.

**Comment by jmecosta** [comment]
you mean a automation api for java to handle microsoft specific stuff? or to write a application in native language to use some of the msbuild api to handle projects? The later can be done, but i havent found any easy way of doing it.  the buildlog approach is dead simple, its done already #399... 

I mean, if you have a good way of implementing a tool to extract a compile_commands.json from a msbuild system i guess it could then be used (i know a few guys that would like that also). but i guess from the plugin side the only change would be only a parser for the compile_commands.json plus the logic to handle the preprocessor based on this

**Comment by LegalizeAdulthood** [comment]
No, "automation" in Windows refers to the ability to automate actions in an application by accessing a COM object that exposes the behavior of the application.  VS has a complete automation API that lets you traverse everything in a C++ solution/project.  Because the automation API exposed by VS is usable from script, you can access everything through javascript.

Oh, and the actual compile commands aren't located in the build log itself, what you see in the build log is something like:
```
1>ClCompile:
1>  dztransferutilitydlg.cpp
```
They are stored in `*.tlog` files, whose format is undocumented and unsupported, but from poking around I determined "hey, this looks like a compile command!" and I stole the contents to make my own `compile_commands.json`.

Any real solution shouldn't rely on these secondary artifacts of the build, but instead use the API provided by VS itself to obtain the project information.  This brings `compile_commands.json` functionality to many, many, many more projects in the Windows space than CMake.  It also enables analysis on code without having to build it.

**Comment by jmecosta** [comment]
i completely agree with you... but we dont have a tool that can do that for
now (not that am aware)..

what we can do now is to use the build log... see
https://github.com/jmecosta/sonar-cxx/blob/feature/create-msbuild-buildlog-parser-agaist-upstream/cxx-squid/src/test/resources/compiler/vc%2B%2B13.txt
it contains a build log taken with /v:detailed that holds all information.
 a example of a compilation unit is

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c
/I"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\"
/I"E:\source\nuget.3.0.0-alpha001-48-1\build\native\../..//build/native/include/"
/I.\interface /I..\tools\interface /I..\memlib\interface /I.. /Z7 /nologo
/W1 /WX- /Od /Oy- /D NT /D OS_NT /D WIN32 /D _MBCS /D ANSI_HEADER /D
USEMEMLIB /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope
/GR
/Fo"D:\prod\SonarQube\cxx\sonar-cxx\integration-tests\testdata\googletest_bullseye_vs_project\ObjDrop\pathhandling\v120\Debug\Win32\v120\PathHandling\\"
/Fd"D:\prod\SonarQube\cxx\sonar-cxx\integration-tests\testdata\googletest_bullseye_vs_project\ObjDrop\pathhandling\v120\Debug\Win32\v120\PathHandling\vc120.pdb"
/Gd /TP /analyze- /errorReport:queue -D_SCL_SECURE_NO_WARNINGS
-D_SCL_SECURE_NO_WARNINGS PathHandle.cpp

this pretty much has all information needed to reconstruct the AST.

Again am not saying that having a automation tool that would create
the compile_commands.json
from msbuild is not the way to go. it is but as long we dont have it we
need to live with the build log... those are easy to maintain since
microsft releases a new compiler maybe every 2 years or so and they dont
change much in these

**Comment by guwirth** [comment]
From my experience: problem is that you can't see all defines. Some are predefined by VS, some are derived from other command line options.

**Comment by LegalizeAdulthood** [comment]
@guwirth True, there are a bunch of defines brought into existence by the compiler and not just the library header files.

However, for those defines it makes sense to define them globally in the sonar project properties because they are identical for all files compiled in that environment.  `compile_commands.json` is about getting the appropriate set of defines and include search paths on a per-translation unit basis, which is currently not supported by the community plugin.

**Comment by jmecosta** [comment]
That makes sense and actually we did exactly this. Seems to work so far
with build log. Our number if parsing errors has decrease quite a lot with
this .

**Comment by jmecosta** [comment]
And by the way I think we should be able to apply this concept to the plugin

**Comment by guwirth** [comment]
Two examples where things are different:

```python
if '/EH' in line:
   #define _CPPUNWIND=1

if '/GR-' not in line
   #define _CPPRTTI=1
```

**Comment by jmecosta** [comment]
The compiler switches are available in the same command line. This
information can be reconstructed. Although it might not be needed! in
compile_commands.json file, the command that you will find there will also
include the options instead of all defines converted per system.

   - *command:* The compile command executed. After JSON unescaping, this
   must be a valid command to rerun the exact compilation step for the
   translation unit in the environment the build system uses. Parameters use
   shell quoting and shell escaping of quotes, with ‘"‘ and ‘\‘ being the
   only special characters. Shell expansion is not supported.

So i see that those options are supposed to be handle by the end user, in
this case our parser.

I dont see this has a big shortcoming of supporting this approach.

Using clang tooling we would get this for free :)

**Comment by guwirth** [comment]
Seems to be less interest in this:  close it
