### ISSUE TITLE
Make "Dependency Structure Matrix" work for multi-module projects

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#509]

**Comment by guwirth** [comment]
@Bertk I'm still not familiar with the dependency checks. How are they working? My current understanding:
* Using the includes to create file dependencies? Currently only file dependencies are supported?
* Are the dependencies also on directory level? Dependency folder1 to folder2?
* Are the dependencies only within one project or also to other project which are already in the SQ database?

Cool would be also to create design rules and issues for violations:
* simple implementation could be: component1 is in folder1; component2 is in folder2; create a check creating an issue if a file in folder1 tries to access folder2

**Comment by Typz** [comment]
Indeed, the sonar-cxx plugin uses includes to create file dependencies, and derive the corresponding directory dependencies.

Then all the dependency matrix is computed at each level (project and directory), and stored as a metric there: as a consequence there cannot be a cross-project matrix, since the metric is always inside a single project....

Now with sonar 5 the computation of the matrix is done by the core itself, so cross project dependencies may be possible... But in any case it seems more a core sonar feature than an improvement in sonar-cxx plugin.

Do you know if this is supported with other languages, e.g. Java?

**Comment by guwirth** [comment]
> Now with sonar 5 the computation of the matrix is done by the core itself, s

@Typz which API is this? Is it also availabe with 4.5.2?

**Comment by guwirth** [comment]
> Do you know if this is supported with other languages, e.g. Java?

I'm sorry I don't use Java.

**Comment by Typz** [comment]
In 4.x, we must compute the dependency matrix, and store them in various metrics.
In 5.x, the values of these metrics are ignored.
I don't remember the names, I'll check later tonight.

**Comment by jens-auer** [comment]
@Typz Could you give me a hint where the dependency matrix is created in SonarQube? I would propose to write a CMake plugin which uses the build information from CMake to define the dependencies to populate the matrix.

**Comment by Typz** [comment]
In the C++ plugin, this is done by the DependencyAnalyzer class: https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/squid/DependencyAnalyzer.java <https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/squid/DependencyAnalyzer.java>

The addFile() method is called for each analyzed file, giving it the list of files it depends. Then all metrics are generated when the save() method is called.

To be clear though: I don’t think there is a way for a plugin to generate multiple dependency matrix/analyses. Using CMake (or any other build system) would give another information, not necessarily better or worse: so it must really be an option to generate dependency from CMake, or some other build system, or just #include’s.

**Comment by jens-auer** [comment]
@Typz In a previous post, you said that the dependency metric is now ignored by SonarQube and the computation is done internally. I was hoping for a pointer to the new computation, and maybe a hint how to feed the information into SonarQube for the new API.

I don't think that the information from the build system at target level, and the information from include structure are mutually exclusive. Rather, I think they are complementary. The build system gives me additional information about artifacts in the system, which cannot be gathered from looking at c++ source files. I think that should be the top-level dependency-structure matrix. For C++, this is basically as much structure information you can get because there is no package/module system, and directory structure does not imply anything else than being a directory (without any other convention).

**Comment by Typz** [comment]
The dependency matrix metric is now computed automatically. However, the dependency metrics (e.g. List of the dependencies of each item, be it a folder/file/...) is still set by each plugin: in case of C++ plugin, in the DependencyAnalyzer class.

**Comment by guwirth** [comment]
Deprecated with SQ 5.6
Removed with #913
