### ISSUE TITLE
CxxCppCheckSensor is not run on SONAR5.2 and sonar-cxx-plugin-0.9.4

### ISSUE THREAD

**Issue by kingwings** [SonarOpenCommunity/sonar-cxx#724]
I have same problem mentioned on https://github.com/SonarOpenCommunity/sonar-cxx/issues/653 . Why I asked again because that issue is closed and I met the problem after I upgrade to SONAR5.2 from 5.1.1 with sonar-cxx-plugin-0.9.4.jar. I checked the SonarQube compatibility matrix, found it is partial supported. Is there any workaround solution, I don't want to downgrade our SONAR. Following is the log snippet:

[INFO] Sensor CxxSquidSensor (done) | time=184918ms
[INFO] Sensor CxxCoverageSensor
[INFO] Sensor CxxCoverageSensor (done) | time=391ms
[INFO] Sensor SCM Sensor
[INFO] No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
[INFO] Sensor SCM Sensor (done) | time=0ms
[INFO] Sensor Code Colorizer Sensor
[INFO] Sensor Code Colorizer Sensor (done) | time=15110ms
[INFO] Sensor CPD Sensor
[INFO] DefaultCpdEngine is used for c++

**Comment by guwirth** [comment]
What exactly is your problem? #653 is about that you have to run cppcheck first to create a report and then use sonar runner to read it.

**Comment by jmecosta** [comment]
for reference you are hitting this bug in the platform: https://jira.sonarsource.com/browse/SONAR-7008

the only way is to apply the patch that it was used to fixed 5.3 on top of 5.2. or you need to wait for 5.3

**Comment by kingwings** [comment]
@ guwirth, Originally, we use 5.1.1 with sonar-cxx-plugin-0.9.4_RC1.jar, it works. But after upgrade to SONAR 5.2. It does not work.
 @jmecosta, I will check this bug, Thank you

**Comment by kingwings** [comment]
SONAR 5.3 will be released: 08/Jan/16. It sounds I have to wait if this problem is related to the bug https://jira.sonarsource.com/browse/SONAR-7008

**Comment by jmecosta** [comment]
Its is related to SONAR-7008, we had to patch SQ 5.2 to make the plugin work. we dont have any plans to support 5.2 since this would require changing the profile keys that would result in your profiles being totally lost after upgrade. 

if SONAR-7008 is release in 5.2.1 (unlikely) then you should be able to use the plugin there, otherwise 5.2 is going to be only partially running (like 10 % running).

you can confirm already that it works if you try 5.3 RC 2. https://www.google.com/url?q=https%3A%2F%2Fsonarsource.bintray.com%2FDistribution%2Fsonarqube%2Fsonarqube-5.3-RC2.zip&sa=D&sntz=1&usg=AFQjCNEgwGhiaVe-_FbJvwU_j5lsXSSD0w

**Comment by guwirth** [comment]
I removed the 5.2 'partial' from the compatibility matrix.

**Comment by kingwings** [comment]
I have tested sonarqube-5.3-RC2 and it has been fixed
