### ISSUE TITLE
template parameter

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#793]
Leftover from #743, use case below is still not supported:

``` C++
// @todo 
// #4, enabled via a template parameter
template<class T,
         typename std::enable_if<
             !std::is_trivially_destructible<T>{} &&
             (std::is_class<T>{} || std::is_union<T>{})
            >::type* = nullptr>
void destroy(T* t)
{
    std::cout << "destroying non-trivially destructible T\n";
    t->~T();
}
```

**Comment by guwirth** [comment]
Hi @wichtounet you are our template expert here. Playing around with this I saw that they also changed the sample here: http://en.cppreference.com/w/cpp/types/enable_if. Which one is valid? Is the above one valid?

```Java
// #4, enabled via a template parameter
template<class T,
         typename std::enable_if<
             !std::is_trivially_destructible<T>{} &&
             (std::is_class<T>{} || std::is_union<T>{}),
            int>::type = 0>
void destroy(T* t)
{
    std::cout << "destroying non-trivially destructible T\n";
    t->~T();
}
````

**Comment by wichtounet** [comment]
Hi @guwirth, 

Both are correct. Although, I would say the second (the new one your just posted) is a bit better because it uses int = 0 instead of void* = nullptr. We can use any type that has constant expression values (integral types and pointer types).

The first one should still work with your parser, but if the second works it's already great :)

**Comment by guwirth** [comment]
@ametselaar we need your help. We have a hard grammar nut to crack.
Do you have some time to have a look to this issue?
