### ISSUE TITLE
No bugs/issues reported in SonarQube. The count is always 0

### ISSUE THREAD

**Issue by fluidjeel** [SonarOpenCommunity/sonar-cxx#947]
I have a C++ multi-module project. As per documentation, I am first generating cppcheck.xml and feeding the same to sonar-runner. Although the cppcheck has issues reported the same doesnt replicate in SonarQube. I dont recieve any errors during scan. I have also tried to scan indvidual components of the multi-module but i still have no success. I have the following Setup:

SonarQube - 5.6.1 LTS
Sonar-cxx plugin - 0.9.7-SNAPSHOT (Because I ran into compatibility issue with google collection )
sonar-runner - 2.4
OS - Ubuntu 14.04

Sonar.project-props file

```
# required metadata
sonar.projectKey=ABC
sonar.projectName=ABC
sonar.projectVersion=1.0


sonar.sources=ABC

# optional description
sonar.projectDescription=ABC project

# path to source directories (required)
sonar.cxx.cppcheck.reportPath=cppcheck.xml
# The value of the property must be the key of the language.
sonar.language=c++
sonar.exclusions=**/*.h
sonar.cxx.cppcheck.path=/usr/bin/cppcheck
```
`

Screenshot of cppcheck result:
![image](https://cloud.githubusercontent.com/assets/10943776/18423347/33f4efb0-7872-11e6-8049-1c9594b80585.png)

Is there any additional config I need to do to make this work. I do get the LOC from the sonar-runner but that it remaining metrics are all 0

Logs From scan: 
[sonar.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/466499/sonar.txt)

PS: The name of the project is not ABC, i have just changed the same for purpose of keep it confidential

**Comment by Bertk** [comment]
Hi,
the log has this messages:
```
04:00:15.377 INFO  - Sensor CxxCppCheckSensor
04:00:15.393 INFO  - Scanner found '1' report files
04:00:15.393 INFO  - Parser will parse '1' report files
04:00:15.393 INFO  - Processing report '/var/lib/sonar-runner-2.4/bin/cppcheck-ulc-uspp-dpdk.xml'
04:00:15.449 WARN  - The report '/var/lib/sonar-runner-2.4/bin/cppcheck-ulc-uspp-dpdk.xml' seems to be empty, ignoring.
04:00:15.449 INFO  - CppCheck Errors processed = 0
04:00:15.449 INFO  - Sensor CxxCppCheckSensor (done) | time=72ms
```
The XML file cannot be read and maybe there is a permission or file encoding issue.

By the way, I use the multi module feature since years but for a windows environment. Typically I store the module related CppCheck report file in the root folder of the module with the name **cppcheck-report.xml**. You also have to make sure to use the correct relative paths for the source files in the CppCheck reports.

You also should consider to add some configurations:
```
sonar.cxx.forceIncludes=sonar_defines.h
sonar.cxx.defines=...
sonar.cxx.includeDirectories=path1,path2,...
sonar.cxx.errorRecoveryEnabled=True
```
I user a sonar_defines.h file to manage specific settings for the platform or compiler. I think this is a handy way to do it and specify pre-defined macros e.g. [gcc macros](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html) .  You can also use ```sonar.cxx.defines``` but this is hard to read if you use many macros.
Your log file shows missing include paths and CXX plug-in parser errors which will be solved with this additional settings.
```
03:59:58.172 WARN  - [/var/lib/sonar-runner-2.4/bin/Harmonics-SCA/ulc-uspp-dpdk/src/Assert.h:18]: cannot find the sources for '#include "rte_debug.h"'
03:59:58.228 WARN  - [/var/lib/sonar-runner-2.4/bin/Harmonics-SCA/ulc-uspp-dpdk/src/PktProcCommon.h:4]: cannot find the sources for '#include <rte_config.h>'

03:59:58.652 ERROR - Unable to parse file: /var/lib/sonar-runner-2.4/bin/Harmonics-SCA/ulc-uspp-dpdk/src/Crc32Ethernet.h
03:59:58.652 ERROR - Parse error at line 167 column 38:

  162: xmm_crc1 = _mm_castps_si128(ps_res1);
  163:     *xmm_crc2 = _mm_castps_si128(ps_res2);
  164:     *xmm_crc3 = _mm_castps_si128(ps_res3);
  165: }
  166: 
  -->  static unsigned __attribute__((aligned(32))) pshufb_shf_table[60] = {
  168:     0x84838281,0x88878685,0x8c8b8a89,0x008f8e8d,
  169:     0x85848382,0x89888786,0x8d8c8b8a,0x01008f8e,
  170:     0x86858483,0x8a898887
```

**Comment by guwirth** [comment]
@fluidjeel maybe some more links worth to read:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
